/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './src/routes/__root'
import { Route as IndexRouteImport } from './src/routes/index'
import { Route as ProfilePrincipalRouteImport } from './src/routes/profile.$principal'
import { Route as AuthProfileRouteImport } from './src/routes/_auth/profile'
import { Route as AuthCreateRouteImport } from './src/routes/_auth/create'
import { Route as AuthPostArweaveIdRouteImport } from './src/routes/_auth/post.$arweaveId'

const AuthRouteLazyRouteImport = createFileRoute('/_auth')()

const AuthRouteLazyRoute = AuthRouteLazyRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./src/routes/_auth/route.lazy').then((d) => d.Route),
)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./src/routes/index.lazy').then((d) => d.Route))
const ProfilePrincipalRoute = ProfilePrincipalRouteImport.update({
  id: '/profile/$principal',
  path: '/profile/$principal',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./src/routes/profile.$principal.lazy').then((d) => d.Route),
)
const AuthProfileRoute = AuthProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthRouteLazyRoute,
} as any).lazy(() =>
  import('./src/routes/_auth/profile.lazy').then((d) => d.Route),
)
const AuthCreateRoute = AuthCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => AuthRouteLazyRoute,
} as any).lazy(() =>
  import('./src/routes/_auth/create.lazy').then((d) => d.Route),
)
const AuthPostArweaveIdRoute = AuthPostArweaveIdRouteImport.update({
  id: '/post/$arweaveId',
  path: '/post/$arweaveId',
  getParentRoute: () => AuthRouteLazyRoute,
} as any).lazy(() =>
  import('./src/routes/_auth/post.$arweaveId.lazy').then((d) => d.Route),
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/create': typeof AuthCreateRoute
  '/profile': typeof AuthProfileRoute
  '/profile/$principal': typeof ProfilePrincipalRoute
  '/post/$arweaveId': typeof AuthPostArweaveIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/create': typeof AuthCreateRoute
  '/profile': typeof AuthProfileRoute
  '/profile/$principal': typeof ProfilePrincipalRoute
  '/post/$arweaveId': typeof AuthPostArweaveIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteLazyRouteWithChildren
  '/_auth/create': typeof AuthCreateRoute
  '/_auth/profile': typeof AuthProfileRoute
  '/profile/$principal': typeof ProfilePrincipalRoute
  '/_auth/post/$arweaveId': typeof AuthPostArweaveIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/create'
    | '/profile'
    | '/profile/$principal'
    | '/post/$arweaveId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/create' | '/profile' | '/profile/$principal' | '/post/$arweaveId'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/_auth/create'
    | '/_auth/profile'
    | '/profile/$principal'
    | '/_auth/post/$arweaveId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRouteLazyRoute: typeof AuthRouteLazyRouteWithChildren
  ProfilePrincipalRoute: typeof ProfilePrincipalRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/$principal': {
      id: '/profile/$principal'
      path: '/profile/$principal'
      fullPath: '/profile/$principal'
      preLoaderRoute: typeof ProfilePrincipalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/profile': {
      id: '/_auth/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthProfileRouteImport
      parentRoute: typeof AuthRouteLazyRoute
    }
    '/_auth/create': {
      id: '/_auth/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof AuthCreateRouteImport
      parentRoute: typeof AuthRouteLazyRoute
    }
    '/_auth/post/$arweaveId': {
      id: '/_auth/post/$arweaveId'
      path: '/post/$arweaveId'
      fullPath: '/post/$arweaveId'
      preLoaderRoute: typeof AuthPostArweaveIdRouteImport
      parentRoute: typeof AuthRouteLazyRoute
    }
  }
}

interface AuthRouteLazyRouteChildren {
  AuthCreateRoute: typeof AuthCreateRoute
  AuthProfileRoute: typeof AuthProfileRoute
  AuthPostArweaveIdRoute: typeof AuthPostArweaveIdRoute
}

const AuthRouteLazyRouteChildren: AuthRouteLazyRouteChildren = {
  AuthCreateRoute: AuthCreateRoute,
  AuthProfileRoute: AuthProfileRoute,
  AuthPostArweaveIdRoute: AuthPostArweaveIdRoute,
}

const AuthRouteLazyRouteWithChildren = AuthRouteLazyRoute._addFileChildren(
  AuthRouteLazyRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRouteLazyRoute: AuthRouteLazyRouteWithChildren,
  ProfilePrincipalRoute: ProfilePrincipalRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
