interface Author {
    id: string;
    first?: string;
    last?: string;
    image: string;
    description: string;
    category: string[];
    cap_first?: string;
    cluster: string;
    books?: string[];
    sentences_json?: string;
    segments_json?: string;
    paragraphs_json?: string;
  }
  

const AUTHOR_INFO: Author[] = [
    {
    "id": "Benjamin Franklin",
    "category": ["Philosophy", "Science", "American History", "Politics", "Inventions", "Philosophy", "Government", "Pioneer"],
    "cluster": "Benjamin_Franklin",
    "image": "Benjamin Franklin.png",
    "description": "Pioneering Visionary & Distinguished Polymath (1706-1790) | Trailblazer in the Discovery of Electricity & Foundational Contributor to the Birth of the United States | Illustrious Founder of the American Philosophical Association | Co-Author of the Declaration of Independence | A luminary who, despite his monumental achievements, once humbly professed, 'I may not be a man of unparalleled greatness, but I am, undeniably, a man of virtue and worth.'",
    },
    {
    "id": "The Bible",
    "category": ["Religion", "Faith", "Christianity", "Orthodoxy", "Islam", "Jesus", "God", "Judaism", "Mysticism", "Life"],
    "cluster": "The_Bible",
    "image": "The Bible.png",
    "description": "The Entire King James Bible, Separated and Indexed by Verse.",
    },
    {
    "id": "Carl Jung",
    "category": ["Psychology", "Mysticism", "Philosophy", "Religion", "Spirituality", "Life", "Psyche", "Analytical Psychology", "Archetypes", "Individuation", "Symbolic Life", "Dreams"],
    "cap_first": "Carl",
    "cluster": "Carl_Jung",
    "first": "carl",
    "last": "jung",
    "image": "carlpfp.png",
    "description": "Psychiatrist & Psychoanalyst (1875-1961) | Founder of Analytical Psychology | Pioneer of the collective unconscious, archetypes, & individuation | \"Show me a sane man and I will cure him for you.\"",
    "books": [  "Psychiatric Studies",
                "Psychogenesis of Mental Disease",
                "Freud and Psychoanalysis",
                "Symbols of Transformation",
                "Psychological Types",
                "Analytical Psychology",
                "Structure and Dynamics of the Psyche",
                "I Archetypes and the Collective Unconscious",
                "II AION Researches into the Phenomenology of the Self",
                "Civilization in Transition",
                "Psychology and Religion West and East",
                "Psychology and Alchemy",
                "Alchemical Studies",
                "Mysterium Coniunctionis",
                "Spirit in Man, Art, and Literature",
                "Practice of Psychotherapy",
                "Development of Personality",
                "The Symbolic Life"
                ],
    "sentences_json": 'https://raw.githubusercontent.com/evanmcfarland/A-Statistical-Approach-to-Happiness/main/data/Carl%20Jung/jung_books_sentences.json',
    "segments_json": 'https://raw.githubusercontent.com/evanmcfarland/A-Statistical-Approach-to-Happiness/main/data/Carl%20Jung/jung_books_segments.json',
    "paragraphs_json": 'https://raw.githubusercontent.com/evanmcfarland/A-Statistical-Approach-to-Happiness/main/data/Carl%20Jung/jung_books_paragraphs.json'
    },
    {
    "id": "Charles Darwin",
    "category": ["Naturalism", "Science", "Evolution", "Discoveries", "Galapagos", "Birds", "Species", "Animals", "Plants", "Fossils", "Geology"],
    "cap_first": "Darwin",
    "cluster": "Charles_Darwin",
    "first": "charles",
    "last": "darwin",
    "image": "darwinpfp.png",
    "description": "Naturalist & Evolutionary Biologist (1809-1882) | Originator of the theory of evolution by natural selection | Wrote 20 books on evolution, geology, & biology | \"It is not the strongest of the species that survives, nor the most intelligent that survives. It is the one that is the most adaptable to change.\"",
    "books": [   'The Voyage of the Beagle',
                 'The Expression of the Emotions in Man and Animals',
                 'On the Origin of Species By Means of Natural Selection Or, the Preservation of Favoured Races in the Struggle for Life',
                 'The Autobiography of Charles Darwin',
                 'Life and Letters of Charles Darwin — Volume 1',
                 'Life and Letters of Charles Darwin — Volume 2',
                 'The Descent of Man, and Selection in Relation to Sex',
                 'Note on the Resemblances and Differences in the Structure and the Development of the Brain in Man and Apes',
                 'The Formation of Vegetable Mould Through the Action of Worms With Observations on Their Habits',
                 'The Movements and Habits of Climbing Plants',
                 'Coral Reefs',
                 'More Letters of Charles Darwin — Volume 1 A Record of His Work in a Series of Hitherto Unpublished Letters',
                 'More Letters of Charles Darwin — Volume 2 A Record of His Work in a Series of Hitherto Unpublished Letters',
                 'Volcanic Islands',
                 'The Variation of Animals and Plants under Domestication',
                 'Geological Observations on South America',
                 'Journal of Researches into the Natural History and Geology of the Countries Visited During the Voyage Round the World of H.M.S. Beagle Under the Command of Captain Fitz Roy, R.N.',
                 'The Different Forms of Flowers on Plants of the Same Species',
                 'Coral Reefs; Volcanic Islands; South American Geology — Complete',
                 'The Effects of Cross & Self-Fertilisation in the Vegetable Kingdom',
                 'The Power of Movement in Plants',
                 'Insectivorous Plants',
                 'The Foundations of the Origin of Species Two Essays written in 1842 and 1844',
                 'A Monograph on the Sub-class Cirripedia (Volume 1 of 2) The Lepadidae; Or, Pedunculated Cirripedes',
                 'Charles Darwin  His Life Told in an Autobiographical Chapter, and in a Selected Series of His Published Letters',
                 'A Monograph on the Sub-class Cirripedia (Volume 2 of 2) The Balanidæ, (or Sessile Cirripedes); the Verrucidæ, etc., etc.',
                 'The zoology of the voyage of H.M.S. Beagle [vol. 1 of 5]  Fossil mammalia',
                 'Darwinism stated by Darwin himself Characteristic passages from the writings of Charles Darwin'
             ],
    "sentences_json": 'https://drive.google.com/file/d/1bgvrTsDUqWYmoUqVeORNVP3Y2CkL7Kv7/view?usp=share_link',
    "segments_json": 'https://drive.google.com/file/d/1Yh2ey5uxoTSEnA9_L5EXrXLWWo1PnzvN/view?usp=share_link',
    "paragraphs_json": 'https://drive.google.com/file/d/1607oWxOQli9BPL-anOmJ3NuSZgfT5hP6/view?usp=share_link'
    },
    {
    "id": "Friedrich Nietzsche",
    "category": ["Philosophy", "Religion", "German", "German Literature", "Sociology", "Morality", "Professor", "Nihilism", "Geneology"],
    "cap_first": "Nietzsche",
    "cluster": "Friedrich_Nietzsche",
    "first": "friedrich",
    "last": "nietzsche",
    "image": "nietzschepfp.png",
    "description": "Philosopher & Cultural Critic (1844-1900) | Exploring ethics, metaphysics, epistemology, nihilism, & aesthetics | Champion of individualism & self-overcoming | \"God is dead, God remains dead, and we have killed him.\"",
    "books": ['Thus Spake Zarathustra  A Book for All and None',
                'Beyond Good and Evil',
                'Homer and Classical Philology',
                'We Philologists Complete Works of Friedrich Nietzsche, Volume 8',
                'The Antichrist',
                'The Case of Wagner, Nietzsche Contra Wagner, and Selected Aphorisms.',
                'On the Future of our Educational Institutions',
                'Human, All-Too-Human  A Book for Free Spirits, Part 2',
                'Thoughts Out of Season, Part II',
                'The Dawn of Day',
                'The Birth of Tragedy; or, Hellenism and Pessimism',
                'Early Greek Philosophy & Other Essays Collected Works, Volume Two',
                'Thoughts out of Season, Part I David Strauss, the Confessor and the Writer - Richard Wagner in Bayreuth.',
                'Human, All-Too-Human  A Book for Free Spirits, Part 1 Complete Works, Volume Six',
                'The Joyful Wisdom ( La Gaya Scienza ) Complete Works, Volume Ten',
                'Ecce Homo Complete Works, Volume Seventeen',
                'The Twilight of the Idols; or, How to Philosophize with the Hammer. The Antichrist Complete Works, Volume Sixteen',
                'The Genealogy of Morals The Complete Works, Volume Thirteen, edited by Dr. Oscar Levy.',
                'The Will to Power  An Attempted Transvaluation of All Values. Book I and II',
                'The Will to Power  An Attempted Transvaluation of All Values. Book III and IV'
            ],
    "sentences_json": 'https://raw.githubusercontent.com/evanmcfarland/A-Statistical-Approach-to-Happiness/main/data/Friedrich%20Nietzsche/nietzsche_books_sentences.json',
    "segments_json": 'https://raw.githubusercontent.com/evanmcfarland/A-Statistical-Approach-to-Happiness/main/data/Friedrich%20Nietzsche/nietzsche_books_segments.json',
    "paragraphs_json": 'https://raw.githubusercontent.com/evanmcfarland/A-Statistical-Approach-to-Happiness/main/data/Friedrich%20Nietzsche/nietzsche_books_paragraphs.json',
    },
    {
    "id": "Grecko Romans",
    "category": ["Philosophy", "Empires", "History", "Politics", "Religion", "Art", "Epic", "Mythology", "Ancient Greece", "Ancient Rome"],
    "cluster": "Greco_Sections",
    "image": "greckopfp.png",
    "description": "The collected works of: Aeschylus | Aestop | Apollonius | Apuleius | Aristophanes | Aristotle | Augustus | Epictetus | Epicurus | Euripides | Galen | Herodotus | Hippocrates| Homer | Julius Caesar | Licretius | Marcus Aurelius | Ovid | Plato | Plotinus | Plutarch | Porphyry | Quintus | Sophocles | Tacitus | Thucydides | Virgil",
    },
    {
    "id": "Henry David Thoreau",
    "category": ["Naturalism", "Philosophy", "Civil Rights", "Literature", "Nature", "Happiness", "American History", "Forest", "Wilderness", "Self-Reliance"],
    "cap_first": "Thoreau",
    "cluster": "Henry_David_Thoreau",
    "first": "henry",
    "last": "thoreau",
    "image": "thoreaupfp.png",
    "description": "Philosopher & Naturalist (1817-1862) | Wrote on the importance of nature, self-reliance, and simplicity | Lived in a cabin in the woods for two years | I show how we all live shares little resemblance with how we ought to live  | \"I went to the woods because I wished to live deliberately, to front only the essential facts of life, and see if I could not learn what it had to teach, and not, when I came to die, discover that I had not lived.\"",
    "sentences_json": 'https://drive.google.com/file/d/1_xtiN7xKjD5DXtCFzkPPLxc2XMO6jO1O/view?usp=share_link',
    "segments_json": 'https://drive.google.com/file/d/1oEY4zWrqb3JGNfMIBDvTatPuNHpy-kzJ/view?usp=share_link',
    "paragraphs_json": 'https://drive.google.com/file/d/1kpFuTYcNgFyEfeq1dLZcduK4uBoXfG-v/view?usp=share_link'
    },
    {"id": "The Occult",
    "category": ["Mysticism", "Psychology", "Religion", "Truth", "Seeking", "Spirituality", "Discovery", "Occult", "Esotericism", "Secrets", "Enlightenment", "Idealism"],
    "cluster": "The_Occult",
   "image": "occultpfp.png",
    "description": "Top 20 Books by Popularity, aggregated by Julie of globalgreyebooks.com: General Book of the Tarot | Black Pullet | Book of Forbidden Knowledge | Grand Grimoire with Great Clavicle of Solomon | The Simon Necronomicon | Book of Ceremonial Magic | Psychic Self Defense | Dogma et Rituel de la Haute Magie Part I | Dogma et Rituel de la Haute Magie Part II | Philosophy of Natural Magic | Goal of Life | Sixth and Seventh Books of Moses | The Chymical Wedding of Christian Rosenkreutz | Secret Teachings of All Ages | Symbolism of the Tarot | The Tarot of the Bohemians | Key of Solomon the King | Mathers Sacred Magic of Abramelin the Mage | Kybalion | Numbers Their Occult Power and Mystic Virtues",
    "books": [
            'The Occult',
            ],
    },
    {
    "id": "Thoth",
    "category": ["Mysticism", "Hermeticism", "Thoth", "Esotericism"],
    "cap_first": "Hermes",
    "cluster": "Hermes_Segments",
    "first": "hermes",
    "last": "trismegistus",
    "image": "hermespfp.png",
    "description": "Ancient Egyptian God of Wisdom (6000-2000 BCE) | Divine scribe & god of wisdom | Inventor of writing, magic & the lunar calendar | Maintaining cosmic balance | Reincarnated in Greece as the Messenger of Gods (1600-300BCE) | Syncretic sage & author of Hermetic texts | Fusing Greek & Egyptian wisdom 'As above, so below; as within, so without.' | Embodying the secrets of the universe",
    "books": [  'A Treatise on Initiations, or Asclepios',
                'Emerald Tablets of Thoth The Atlantian',
                'Fragments of the Book of Hermes to his Son Tatios',
                'Fragments of the Writings of Hermes to Ammon',
                'Fragments of the Writings of Hermes',
                'The Corpus Hermeticum I. Poemandres, the Shepherd of Men',
                'The Corpus Hermeticum II. To Asclepius',
                'The Corpus Hermeticum III. The Sacred Sermon',
                'The Corpus Hermeticum IV. The Cup or Monad',
                'The Corpus Hermeticum V. Though Unmanifest God Is Most Manifest',
                'The Corpus Hermeticum VI. In God Alone Is Good And Elsewhere Nowhere',
                'The Corpus Hermeticum VII. The Greatest Ill Among Men is Ignorance of God',
                'The Corpus Hermeticum VIII. That No One of Existing Things doth Perish, but Men in Error Speak of Their Changes as Destructions and as Deaths',
                'The Corpus Hermeticum IV. On Thought and Sense',
                'The Corpus Hermeticum X. The Key',
                'The Corpus Hermeticum XI. Mind Unto Hermes',
                'The Corpus Hermeticum XII. About The Common Mind',
                'The Corpus Hermeticum XIII. The Secret Sermon on the Mountain',
                'The Corpus Hermeticum XIV. A Letter of Thrice-Greatest Hermes to Asclepius',
                'The Corpus Hermeticum XV. The Definitions of Asclepius unto King Ammon',
                'The Corpus Hermeticum XVI. Of Asclepius to the King',
                'The The Corpus Hermeticum XVII. The Encomium of Kings',
                'The Definitions of Asclepios',
                'The Perfect Sermon, or The Asclepius',
                'The Virgin of The World'
            ],
    "sentences_json": 'https://raw.githubusercontent.com/evanmcfarland/A-Statistical-Approach-to-Happiness/main/data/hermes/hermes_books_sentences.json',
    "segments_json": 'https://raw.githubusercontent.com/evanmcfarland/A-Statistical-Approach-to-Happiness/main/data/hermes/hermes_books_segments.json',
    "paragraphs_json": 'https://raw.githubusercontent.com/evanmcfarland/A-Statistical-Approach-to-Happiness/main/data/hermes/hermes_books_paragraphs.json'
    },
    {
        "id": "Sigmund Freud",
        "category": ["Psychology", "Sexuality", "Psychoanalysis", "Freud", "Dreams", "Oedipus Complex", "Materialism"],
        "cluster": "Sigmund_Freud",
        "first": "sigmund",
        "last": "freud",
        "image": "freudpfp.png",
        "description": "Father of Psychoanalysis (1856-1939) | My theories on the unconscious mind revolutionized psychology | My work on dreams, the ego, and the id are still studied today | My ideas on the human psyche have influenced countless artists and writers | My work on sexuality and the Oedipus complex are still debated today | \"The mind is like an iceberg, it floats with one-seventh of its bulk above water.\"",
        "books": [
                'A General Introduction to Psychoanalysis',
                'tbd'
                ],
        "sentences_json": 'https://raw.githubusercontent.com/evanmcfarland/A-Statistical-Approach-to-Happiness/main/data/sigmund_freud/sigmund_freud_sentences.json',
    },
];


export default AUTHOR_INFO;





        // {
    // "id": "Camille Flammarion",
    // "category": ["Mysticism", "Astronomy"],
    // "cap_first": "Flammarion",
    // "cluster": "Flammarion_Segments",
    // "first": "flammarion",
    // "last": "camille",
    // "image": "flammarionpfp.png",
    // "description": "Astronomer & Popular Science Writer (1842-1925) | Author of the first popular astronomy book | Wrote over 100 books on science, philosophy, & history | Mixing Science and Mysticism, Psychology and Spirit, Astrology and Wisdom | \"The universe is a great machine, and the human mind is a great key.\"",
    // "books": [
    //             'Astronomical Myths',
    //             'Astronomy for Amateurs',
    //             'Death and its Mystery',
    //             'Haunted Houses',
    //             'Lumen',
    //             'Mysterious Psychic Forces',
    //             'Omega',
    //             'Popular Astronomy; a general description of the heavens',
    //             'The Marvels of the Heavens',
    //             'The Unknown',
    //             'Thunder and Lightning',
    //             'Travels in the Air',
    //             'Urania'
    //         ],
    // "sentences_json": 'https://raw.githubusercontent.com/evanmcfarland/A-Statistical-Approach-to-Happiness/main/Camille%20Flammarion/flammarion_books_sentences.json',
    // "segments_json": 'https://raw.githubusercontent.com/evanmcfarland/A-Statistical-Approach-to-Happiness/main/Camille%20Flammarion/flammarion_books_segments.json',
    // "paragraphs_json": 'https://raw.githubusercontent.com/evanmcfarland/A-Statistical-Approach-to-Happiness/main/Camille%20Flammarion/flammarion_books_paragraphs.json'
    // },

    //     {
//     "id": "Herman Melville",
//     "category": ["Literature"],
//     "cap_first": "Melville",
//     "cluster": "Melville_Segments",
//     "first": "herman",
//     "last": "melville",
//     "image": "melvillepfp.png",
//     "description": "Masterful Author & Storyteller (1819-1891) | Unraveling the depths of human experience | Redefined American literature with Moby-Dick | Explored life at sea & society's complexities | Wrote on culture, philosophy, and human nature | Bridged the realms of fiction and reality | \"It is better to fail in originality than to succeed in imitation.\"",
//     "books": ['Moby Dick  or  The Whale', 'Typee  A Romance of the South Seas', 'I and My Chimney', 'Omoo  Adventures in the South Seas', 'Redburn  His First Voyage Being the Sailor Boy Confessions and Reminiscences of the Son Of A Gentleman in the Merchant Navy', 'White Jacket  Or  The World on a Man of War', 'Bartleby  the Scrivener  A Story of Wall Street', 'Battle Pieces and Aspects of the War', 'John Marr and Other Poems', 'Mardi  and A Voyage Thither  Vol  I', 'Mardi  and A Voyage Thither  Vol  II', 'Israel Potter  His Fifty Years of Exile', 'The Piazza Tales', 'The Confidence Man  His Masquerade', 'Pierre  or The Ambiguities', 'The Apple Tree Table  and Other Sketches'],
//     "sentences_json": 'https://drive.google.com/file/d/1yGLCs5RC0d-IRqCjeT12wv9A86Z4YKs4/view?usp=share_link',
//     "segments_json": 'https://drive.google.com/file/d/1i4vZ0loKVTXkGF5BtXwnoSZawwz_57RY/view?usp=share_link',
//     "paragraphs_json": 'https://drive.google.com/file/d/16t4weUZU5XqYWFFyaD7YhrRwk92YqMBu/view?usp=share_link'
//     },
//     {
//     "id": "Jane Austen",
//     "category": ["Literature", "Romance"],
//     "cap_first": "Jane",
//     "cluster": "Jane_Segments",
//     "first": "jane",
//     "last": "austen",
//     "image": "austenpfp.png",
//     "description": "English Novelist of Manners (1775-1817) | Author of Pride & Prejudice, Sense & Sensibility, Emma, & Persuasion | Masterfully dissecting social norms with wit | \"I declare after all there is no enjoyment like reading! How much sooner one tires of anything than of a book!\"",
//     "books": [
//             'Emma',
//             'Lady Susan',
//             'Love and Friendship',
//             'Mansfield Park',
//             'Northanger Abbey',
//             'Persuasion',
//             'Pride and Prejudice',
//             'Sense and Sensibility',
//             'The Letters of Jane Austen'
//             ],
//     "sentences_json": 'https://raw.githubusercontent.com/evanmcfarland/A-Statistical-Approach-to-Happiness/main/Jane%20Austen/jane_books_sentences.json',
//     "segments_json": 'https://raw.githubusercontent.com/evanmcfarland/A-Statistical-Approach-to-Happiness/main/Jane%20Austen/jane_books_segments.json',
//     "paragraphs_json": 'https://raw.githubusercontent.com/evanmcfarland/A-Statistical-Approach-to-Happiness/main/Jane%20Austen/jane_books_paragraphs.json'

//     },
//     {
//     "id": "John Dewey",
//     "category": ["Psychology", "Philosophy"],
//     "cap_first": "Dewey",
//     "cluster": "Dewey_Segments",
//     "first": "john",
//     "last": "dewey",
//     "image": "deweypfp.png",
//     "description": "American Philosopher & Educator (1859-1952) | Educator, Founder of the Philosophical School of Pragmatism, Avid Supporter of the Arts | Author of Democracy & Education, Experience & Nature, & The Public and Its Problems | \"Education is not preparation for life; education is life itself.\"",
//     "books": [
//             'A Common Faith',
//             'Art As An Experience',
//             'China, Japan and the U.S.A.',
//             'Creative Intelligence; Essays in Pragmatic Attitude',
//             'Democracy and Education',
//             'Essays in Experimental Logic',
//             'Ethics',
//             'Experience And Nature',
//             'Freedom and Culture',
//             'German Philosophy and Politics',
//             'How we Think',
//             'Human Nature and Conduct',
//             'Leibnizs New Essays Concerning the Human Understanding',
//             'Letters from China and Japan',
//             'Logic The Theory Of Inquiry',
//             'Moral Principles in Education',
//             'Outlines of a Critical Theory of Ethics',
//             'Philosophy And Civilization',
//             'Psychology and Social Practice',
//             'Reconstruction in Philosophy',
//             'Schools of To-morrow',
//             'Studies in Logical Theory',
//             'The Child and the Curriculum',
//             'The Influence of Darwin on Philosophy, and other essays in contemporary thought',
//             'The School and Society'
//             ],
//     "sentences_json": 'https://raw.githubusercontent.com/evanmcfarland/A-Statistical-Approach-to-Happiness/main/John%20Dewey/dewey_books_sentences.json',
//     "segments_json": 'https://raw.githubusercontent.com/evanmcfarland/A-Statistical-Approach-to-Happiness/main/John%20Dewey/dewey_books_segments.json',
//     "paragraphs_json": 'https://raw.githubusercontent.com/evanmcfarland/A-Statistical-Approach-to-Happiness/main/John%20Dewey/dewey_books_paragraphs.json'
//     },
    // {
    //     "id": "John Stuart Mill",
    //     "category": ["Philosophy", "Politics", "Economics"],
    //     "cap_first": "Mill",
    //     "first": "john",
    //     "last": "stuart mill",
    //     "image": "millpfp.png",
    //     "description" : "Philosopher, Economist, and Political Thinker (1806-1873) | My works on liberty, democracy, and utilitarianism have had a profound impact on political theory | I championed individual rights and the importance of social justice | Through my essays and treatises, I advocated for education and intellectual development as a means to improve society | A leading figure in the 19th century Enlightenment, I sought to reconcile reason and human emotion | \"The only purpose for which power can be rightfully exercised over any member of a civilized community, against his will, is to prevent harm to others. That is my fundamental principle of morality.\"",
    //     "books": ["tbd"],
    //     "sentences_json": "tbd",
    //     "segments_json": "tbd",
    //     "paragraphs_json": "tbd"
    // },
//     {
//     "id": "Mary Shelley",
//     "category": ["Literature", "Romance"],
//     "cap_first": "Mary",
//     "cluster": "Mary_Segments",
//     "first": "mary",
//     "last": "shelley",
//     "image": "marypfp.png",
//     "description": "British Novelist (1797-1851) | Mother of Science Fiction | Author of Frankenstein | Delving into the human condition, the consequences of scientific progress, & pushing the boundaries of literature | Bold, groundbreaking storyteller | \"Beware; for I am fearless, and therefore powerful.\"",
//     "books": [  'Eminent literary and scientific men of Italy, Spain, and Portugal. Vol. 1',
//                 'Eminent literary and scientific men of Italy, Spain, and Portugal. Vol. 2',
//                 'Eminent literary and scientific men of Italy, Spain, and Portugal. Vol. 3',
//                 'Falkner; A Novel',
//                 'Frankenstein; Or, The Modern Prometheus',
//                 'History of a Six Weeks Tour',
//                 'Lives of the most eminent literary and scientific men of France, Vol. 1',
//                 'Lives of the most eminent literary and scientific men of France, Vol. 2',
//                 'Lodore Vol. 1',
//                 'Lodore Vol. 2',
//                 'Lodore Vol. 3',
//                 'Mathilda',
//                 'Notes to the Complete Poetical Work of Percy Bysshe Shelley',
//                 'Proserpine and Midas',
//                 'Tales and Stories',
//                 'The Fortunes of Perkin Warbeck',
//                 'The Heir of Mondolfo',
//                 'The Last Man',
//                 'Valperga Vol. 1',
//                 'Valperga Vol. 2',
//                 'Valperga Vol. 3'
//             ],
//     "sentences_json": 'https://raw.githubusercontent.com/evanmcfarland/A-Statistical-Approach-to-Happiness/main/data/Mary%20Shelley/mary_books_sentences.json',
//     "segments_json": 'https://raw.githubusercontent.com/evanmcfarland/A-Statistical-Approach-to-Happiness/main/data/Mary%20Shelley/mary_books_segments.json',
//     "paragraphs_json": 'https://raw.githubusercontent.com/evanmcfarland/A-Statistical-Approach-to-Happiness/main/data/Mary%20Shelley/mary_books_paragraphs.json'
//     },
    // {"id": "Niccolo Machiavelli",
    // "category": ["Philosophy", "Politics"],
    // "cap_first": "Machiavelli",
    // "first": "niccolo",
    // "last": "machiavelli",
    // "image": "machiavellipfp.png",
    // "description": "Political Philosopher & Diplomat (1469-1527) | Master of Realpolitik | Architect of \"The Prince\" | Advocate of power dynamics & political cunning | Igniting the pragmatic approach in statecraft, challenging morality and ethics. | \"It is better to be feared than loved, if you cannot be both.\"",
    // "books": [ 'Discourses on the First Decade of Titus Livius',
    //             'TBD'
    //         ],
    // "sentences_json": 'nothting',
    // "segments_json": 'doublecheck gutenburg has everything.',
    // "paragraphs_json": 'doublecheck gutenburg has everything.'
    // },
//     {
//     "id": "Richard Wagner",
//     "category": ["Music", "Philosophy"],
//     "cap_first": "Wagner",
//     "cluster": "Wagner_Segments",
//     "first": "wagner",
//     "last": "richard",
//     "image": "wagnerpfp.png",
//     "description": "Renaissance Man & Composer (1813-1883) | Unveiling the creative process | Redefined the concept of music and opera | Influenced the modern theatrical form | Wrote on music, philosophy, and politics | Bridged the arts, sciences, and humanities | \"Music is the language of the heart without words.\"",
//     "books" : [
//                 'Collection of Richard Wagner Prose Works',
//                 'Correspondence of Wagner and Liszt, Volume 1',
//                 'Correspondence of Wagner and Liszt, Volume 2',
//                 'Jewishness in Music',
//                 'My Life Volume 1',
//                 'My Life Volume 2',
//                 'On Conducting; A Treatise on Style in the Execution of Classical Music',
//                 'Opera & Drama Volume II',
//                 'Opera and Drama Volume I',
//                 'Parsifal; A Drama by Wagner',
//                 'Siegfried and The Twilight of the Gods',
//                 'Stories from Wagner',
//                 'The Art-Work of the Future'
//             ],
//     "sentences_json": 'https://raw.githubusercontent.com/evanmcfarland/A-Statistical-Approach-to-Happiness/main/Richard%20Wagner/wagner_books_sentences.json',
//     "segments_json": 'https://raw.githubusercontent.com/evanmcfarland/A-Statistical-Approach-to-Happiness/main/Richard%20Wagner/wagner_books_segments.json',
//     "paragraphs_json": 'https://raw.githubusercontent.com/evanmcfarland/A-Statistical-Approach-to-Happiness/main/Richard%20Wagner/wagner_books_paragraphs.json'
//     },
    // {
    //     "id": "Frederick Douglass",
    //     "category": ["Civil Rights"],
    //     "cap_first": "Douglass",
    //     "first": "frederick",
    //     "last": "douglass",
    //     "image": "douglasspfp.png",
    //     "description": "🇺🇸 Abolitionist & Social Reformer (1818-1895) | Breaking the chains of slavery, advocating for human rights, & championing education | Symbol of resistance against racial segregation & beacon for equality | \"Without struggle, there is no progress.\"",
    //     "books": [  "My Bondage and My Freedom",
    //                 "TBD",
    //             ],
    //     "sentences_json": "Tbd",
    //     "segments_json": "Tbd",
    //     "paragraphs_json": "Tbd"
    // },

//     {
//     "id": "Fyodor Dostoevsky",
//     "category": ["Literature", "Psychology"],
//     "cap_first": "Dostoyevsky",
//     "cluster": "Dostoyevsky_Segments",
//     "first": "fyodor",
//     "last": "dostoevsky",
//     "image": "dostoevskypfp.png",
//     "description": "Novelist & Philosopher (1821-1881) | Wrote on the human condition & the struggle between good & evil | From near-execution to literary greatness: Dostoevsky's fearless critiques of the Tsarist regime. | \"The degree of civilization in a society can be judged by entering its prisons.\"",
//     "books": [   
//                 'Notes from the Underground',
//                 'The Gambler',
//                 'Poor Folk',
//                 'Crime and Punishment',
//                 'The Idiot',
//                 'The Possessed',
//                 'The Grand Inquisitor',
//                 'The Brothers Karamazov',
//                 'White Nights and Other Stories',
//                 'The House of the Dead',
//                 "Stavrogin's Confession and The Plan of The Life of a Great Sinner"
//             ],
//     "sentences_json": 'https://drive.google.com/file/d/1aHSGMN1qfYM341g3784C1QOL6McNDNbn/view?usp=share_link',
//     "segments_json": 'https://drive.google.com/file/d/1xvqD_iA2A__Z8uPwRQXvNN5n7KbeBKKd/view?usp=share_link',
//     "paragraphs_json": 'https://drive.google.com/file/d/1IxFU0YXhyNC-8jjPzu5Y4mXVyzRTAdCc/view?usp=share_link'  
//     },
//     {
//     "id": "Shakespeare",
//     "category": ["Literature"],
//     "cap_first": "Shakespeare",
//     "cluster": "Shakespeare_Segments",
//     "first": "william",
//     "last": "shakespeare",
//     "image": "shakespearepfp.png",
//     "description": "Master of Intrigue & Timeless Tales (1564-1616) | The Bard of Avon, creator of iconic characters | Enriched the English language with countless phrases & expressions | Whose plays inspired generations of writers, composers, & filmmakers | Wove romance, tragedy, & comedy into unforgettable stories | Famed for depicting the human condition with unrivaled insight | \"To be or not to be, that's the question I'll forever be remembered for!\"",
//     "books" : [
//                     'Shakespeares Sonnets',
//                     'Venus and Adonis',
//                     'King Richard III',
//                     'The Comedy of Errors',
//                     'The Taming of the Shrew',
//                     'The Two Gentlemen of Verona',
//                     'Loves Labours Lost',
//                     'King John',
//                     'A Midsummer Nights Dream',
//                     'The Merchant of Venice',
//                     'The Merry Wives of Windsor',
//                     'As You Like It',
//                     'Alls Well That Ends Well',
//                     'Measure for Measure',
//                     'Cymbeline',
//                     'The Winters Tale',
//                     'The Tempest',
//                     'A Lovers Complaint',
//                     'The Rape of Lucrece',
//                     'King Richard II',
//                     'Romeo and Juliet',
//                     'Julius Caesar',
//                     'The Phoenix and the Turtle',
//                     'Macbeth',
//                     'Antony and Cleopatra',
//                     'Pericles  Prince of Tyre',
//                     'The Passionate Pilgrim',
//                     'Sonnets on Sundry Notes of Music',
//                     'Titus Andronicus',
//                     'King Henry IV  Part 1',
//                     'King Henry IV  Part 2',
//                     'King Henry V',
//                     'Hamlet',
//                     'Othello',
//                     'King Lear',
//                     'Coriolanus',
//                     'Timon of Athens',
//                     'King Henry VIII',
//                     'Twelfth Night',
//                     'Much Ado About Nothing'
//             ],
//     "sentences_json": 'https://drive.google.com/file/d/1PuKbxzoAmgU8iwMBl6AlYroIBWdNWoNX/view?usp=share_link',
//     "segments_json": 'https://drive.google.com/file/d/1fF17pqlYYZBFoGH3MwBDs_VlsQWhbZCW/view?usp=share_link',
//     "paragraphs_json": 'https://drive.google.com/file/d/1fF17pqlYYZBFoGH3MwBDs_VlsQWhbZCW/view?usp=share_link'
//     },
    // {
    // "id": "Rene Descartes",
    // "category": ["Philosophy", "Mathematics"],
    // "cap_first": "Rene",
    // "first": "rene",
    // "last": "descartes",
    // "image": "descartespfp.png",
    // "description": "Philosopher, Mathematician & Scientist (1596-1650) | Father of Modern Philosophy | Pioneer of \"Meditations on First Philosophy\" | Champion of methodic doubt & rationalism | Propelling humanity forward, one rational thought at a time. | \"Cogito, ergo sum\" (I think, therefore I am)",
    // "books" : [
    //                 'A Discourse on Method',
    //                 'TBD'
    //         ],
    // "sentences_json": 'tbd',
    // "segments_json": 'tbd',
    // "paragraphs_json": 'tbd'
    // }
    //     {
//     "id": "Voltaire",
//     "category": ["Philosophy"],
//     "cap_first": "Voltaire",
//     "cluster": "Voltaire_Segments",
//     "first": "voltaire",
//     "last": "voltaire",
//     "image": "voltairepfp.png",
//     "description": "François-Marie Arouet: Acclaimed Satirist & Enlightenment Luminary (1694-1778) | As the Sage of Ferney, my wit and wisdom have left an indelible mark | I fought against tyranny with every breath | My passion for human rights inspired the French Revolution | Through satire, I challenged society's ills and shaped social reform | Seeded the philosophy of the Enlightenment, nurturing reason and intellectual curiosity | \"I may not agree with what you say, but I will defend to the death your right to say it - that is the legacy I leave behind!\"",
//     "books": [   
//                 'A Philosophical Dictionary, Volume 1',
//                 'A Philosophical Dictionary, Volume 2',
//                 'A Philosophical Dictionary, Volume 3',
//                 'A Philosophical Dictionary, Volume 4',
//                 'A Philosophical Dictionary, Volume 5',
//                 'A Philosophical Dictionary, Volume 6',
//                 'A Philosophical Dictionary, Volume 7',
//                 'A Philosophical Dictionary, Volume 8',
//                 'A Philosophical Dictionary, Volume 9',
//                 'A Philosophical Dictionary, Volume 10',
//                 'Candide',
//             'Letters on England',
//             'Micromegas',
//             'Socrates',
//             'Superstition In All Ages',
//             'The Fourth Book of Virgils Aeneid and the Ninth Book of Voltaires Henriad',
//             'The History of Peter the Great, Emperor of Russia',
//             'The Works of Voltaire, Vol. IV of XLIII.',
//             'Voltaires Philosophical Dictionary',
//             'Voltaires Romances, Complete in One Volume',
//             'Zadig'
//             ],
//     "sentences_json": 'https://drive.google.com/file/d/1q6K23Gkj9pGCUf1_QoHkepPMQJq7JYD1/view?usp=share_link',
//     "segments_json": 'https://drive.google.com/file/d/11cPpdwHeaef09qSueQLGnwdhHg05dFF0/view?usp=share_link',
//     "paragraphs_json": 'https://drive.google.com/file/d/1ZkBw31QVBPNapLnHlwyHAfn_GH18xlYd/view?usp=share_link'
//     },