/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './src/routes/__root'
import { Route as IndexRouteImport } from './src/routes/index'
import { Route as AuthUploadRouteImport } from './src/routes/_auth/upload'
import { Route as AuthShelfRouteImport } from './src/routes/_auth/shelf'
import { Route as AuthMarketRouteImport } from './src/routes/_auth/market'
import { Route as AuthLibraryRouteImport } from './src/routes/_auth/library'
import { Route as AuthBrowseRouteImport } from './src/routes/_auth/browse'
import { Route as AuthStudioPrincipalRouteImport } from './src/routes/_auth/studio.$principal'
import { Route as AuthArchivePrincipalRouteImport } from './src/routes/_auth/archive.$principal'

const AuthRouteLazyRouteImport = createFileRoute('/_auth')()

const AuthRouteLazyRoute = AuthRouteLazyRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./src/routes/_auth/route.lazy').then((d) => d.Route),
)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./src/routes/index.lazy').then((d) => d.Route))
const AuthUploadRoute = AuthUploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => AuthRouteLazyRoute,
} as any).lazy(() =>
  import('./src/routes/_auth/upload.lazy').then((d) => d.Route),
)
const AuthShelfRoute = AuthShelfRouteImport.update({
  id: '/shelf',
  path: '/shelf',
  getParentRoute: () => AuthRouteLazyRoute,
} as any).lazy(() =>
  import('./src/routes/_auth/shelf.lazy').then((d) => d.Route),
)
const AuthMarketRoute = AuthMarketRouteImport.update({
  id: '/market',
  path: '/market',
  getParentRoute: () => AuthRouteLazyRoute,
} as any).lazy(() =>
  import('./src/routes/_auth/market.lazy').then((d) => d.Route),
)
const AuthLibraryRoute = AuthLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => AuthRouteLazyRoute,
} as any).lazy(() =>
  import('./src/routes/_auth/library.lazy').then((d) => d.Route),
)
const AuthBrowseRoute = AuthBrowseRouteImport.update({
  id: '/browse',
  path: '/browse',
  getParentRoute: () => AuthRouteLazyRoute,
} as any).lazy(() =>
  import('./src/routes/_auth/browse.lazy').then((d) => d.Route),
)
const AuthStudioPrincipalRoute = AuthStudioPrincipalRouteImport.update({
  id: '/studio/$principal',
  path: '/studio/$principal',
  getParentRoute: () => AuthRouteLazyRoute,
} as any).lazy(() =>
  import('./src/routes/_auth/studio.$principal.lazy').then((d) => d.Route),
)
const AuthArchivePrincipalRoute = AuthArchivePrincipalRouteImport.update({
  id: '/archive/$principal',
  path: '/archive/$principal',
  getParentRoute: () => AuthRouteLazyRoute,
} as any).lazy(() =>
  import('./src/routes/_auth/archive.$principal.lazy').then((d) => d.Route),
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/browse': typeof AuthBrowseRoute
  '/library': typeof AuthLibraryRoute
  '/market': typeof AuthMarketRoute
  '/shelf': typeof AuthShelfRoute
  '/upload': typeof AuthUploadRoute
  '/archive/$principal': typeof AuthArchivePrincipalRoute
  '/studio/$principal': typeof AuthStudioPrincipalRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/browse': typeof AuthBrowseRoute
  '/library': typeof AuthLibraryRoute
  '/market': typeof AuthMarketRoute
  '/shelf': typeof AuthShelfRoute
  '/upload': typeof AuthUploadRoute
  '/archive/$principal': typeof AuthArchivePrincipalRoute
  '/studio/$principal': typeof AuthStudioPrincipalRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteLazyRouteWithChildren
  '/_auth/browse': typeof AuthBrowseRoute
  '/_auth/library': typeof AuthLibraryRoute
  '/_auth/market': typeof AuthMarketRoute
  '/_auth/shelf': typeof AuthShelfRoute
  '/_auth/upload': typeof AuthUploadRoute
  '/_auth/archive/$principal': typeof AuthArchivePrincipalRoute
  '/_auth/studio/$principal': typeof AuthStudioPrincipalRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/browse'
    | '/library'
    | '/market'
    | '/shelf'
    | '/upload'
    | '/archive/$principal'
    | '/studio/$principal'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/browse'
    | '/library'
    | '/market'
    | '/shelf'
    | '/upload'
    | '/archive/$principal'
    | '/studio/$principal'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/_auth/browse'
    | '/_auth/library'
    | '/_auth/market'
    | '/_auth/shelf'
    | '/_auth/upload'
    | '/_auth/archive/$principal'
    | '/_auth/studio/$principal'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRouteLazyRoute: typeof AuthRouteLazyRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/upload': {
      id: '/_auth/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof AuthUploadRouteImport
      parentRoute: typeof AuthRouteLazyRoute
    }
    '/_auth/shelf': {
      id: '/_auth/shelf'
      path: '/shelf'
      fullPath: '/shelf'
      preLoaderRoute: typeof AuthShelfRouteImport
      parentRoute: typeof AuthRouteLazyRoute
    }
    '/_auth/market': {
      id: '/_auth/market'
      path: '/market'
      fullPath: '/market'
      preLoaderRoute: typeof AuthMarketRouteImport
      parentRoute: typeof AuthRouteLazyRoute
    }
    '/_auth/library': {
      id: '/_auth/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof AuthLibraryRouteImport
      parentRoute: typeof AuthRouteLazyRoute
    }
    '/_auth/browse': {
      id: '/_auth/browse'
      path: '/browse'
      fullPath: '/browse'
      preLoaderRoute: typeof AuthBrowseRouteImport
      parentRoute: typeof AuthRouteLazyRoute
    }
    '/_auth/studio/$principal': {
      id: '/_auth/studio/$principal'
      path: '/studio/$principal'
      fullPath: '/studio/$principal'
      preLoaderRoute: typeof AuthStudioPrincipalRouteImport
      parentRoute: typeof AuthRouteLazyRoute
    }
    '/_auth/archive/$principal': {
      id: '/_auth/archive/$principal'
      path: '/archive/$principal'
      fullPath: '/archive/$principal'
      preLoaderRoute: typeof AuthArchivePrincipalRouteImport
      parentRoute: typeof AuthRouteLazyRoute
    }
  }
}

interface AuthRouteLazyRouteChildren {
  AuthBrowseRoute: typeof AuthBrowseRoute
  AuthLibraryRoute: typeof AuthLibraryRoute
  AuthMarketRoute: typeof AuthMarketRoute
  AuthShelfRoute: typeof AuthShelfRoute
  AuthUploadRoute: typeof AuthUploadRoute
  AuthArchivePrincipalRoute: typeof AuthArchivePrincipalRoute
  AuthStudioPrincipalRoute: typeof AuthStudioPrincipalRoute
}

const AuthRouteLazyRouteChildren: AuthRouteLazyRouteChildren = {
  AuthBrowseRoute: AuthBrowseRoute,
  AuthLibraryRoute: AuthLibraryRoute,
  AuthMarketRoute: AuthMarketRoute,
  AuthShelfRoute: AuthShelfRoute,
  AuthUploadRoute: AuthUploadRoute,
  AuthArchivePrincipalRoute: AuthArchivePrincipalRoute,
  AuthStudioPrincipalRoute: AuthStudioPrincipalRoute,
}

const AuthRouteLazyRouteWithChildren = AuthRouteLazyRoute._addFileChildren(
  AuthRouteLazyRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRouteLazyRoute: AuthRouteLazyRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
