/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './src/routes/__root'
import { Route as RulesRouteImport } from './src/routes/rules'
import { Route as FairplayRouteImport } from './src/routes/fairplay'
import { Route as IndexRouteImport } from './src/routes/index'
import { Route as AuthProfileRouteImport } from './src/routes/_auth/profile'
import { Route as AuthMinesRouteImport } from './src/routes/_auth/mines'

const AuthRouteLazyRouteImport = createFileRoute('/_auth')()

const AuthRouteLazyRoute = AuthRouteLazyRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./src/routes/_auth/route.lazy').then((d) => d.Route),
)
const RulesRoute = RulesRouteImport.update({
  id: '/rules',
  path: '/rules',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./src/routes/rules.lazy').then((d) => d.Route))
const FairplayRoute = FairplayRouteImport.update({
  id: '/fairplay',
  path: '/fairplay',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./src/routes/fairplay.lazy').then((d) => d.Route))
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./src/routes/index.lazy').then((d) => d.Route))
const AuthProfileRoute = AuthProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthRouteLazyRoute,
} as any).lazy(() =>
  import('./src/routes/_auth/profile.lazy').then((d) => d.Route),
)
const AuthMinesRoute = AuthMinesRouteImport.update({
  id: '/mines',
  path: '/mines',
  getParentRoute: () => AuthRouteLazyRoute,
} as any).lazy(() =>
  import('./src/routes/_auth/mines.lazy').then((d) => d.Route),
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/fairplay': typeof FairplayRoute
  '/rules': typeof RulesRoute
  '/mines': typeof AuthMinesRoute
  '/profile': typeof AuthProfileRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/fairplay': typeof FairplayRoute
  '/rules': typeof RulesRoute
  '/mines': typeof AuthMinesRoute
  '/profile': typeof AuthProfileRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/fairplay': typeof FairplayRoute
  '/rules': typeof RulesRoute
  '/_auth': typeof AuthRouteLazyRouteWithChildren
  '/_auth/mines': typeof AuthMinesRoute
  '/_auth/profile': typeof AuthProfileRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/fairplay' | '/rules' | '/mines' | '/profile'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/fairplay' | '/rules' | '/mines' | '/profile'
  id:
    | '__root__'
    | '/'
    | '/fairplay'
    | '/rules'
    | '/_auth'
    | '/_auth/mines'
    | '/_auth/profile'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FairplayRoute: typeof FairplayRoute
  RulesRoute: typeof RulesRoute
  AuthRouteLazyRoute: typeof AuthRouteLazyRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rules': {
      id: '/rules'
      path: '/rules'
      fullPath: '/rules'
      preLoaderRoute: typeof RulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fairplay': {
      id: '/fairplay'
      path: '/fairplay'
      fullPath: '/fairplay'
      preLoaderRoute: typeof FairplayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/profile': {
      id: '/_auth/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthProfileRouteImport
      parentRoute: typeof AuthRouteLazyRoute
    }
    '/_auth/mines': {
      id: '/_auth/mines'
      path: '/mines'
      fullPath: '/mines'
      preLoaderRoute: typeof AuthMinesRouteImport
      parentRoute: typeof AuthRouteLazyRoute
    }
  }
}

interface AuthRouteLazyRouteChildren {
  AuthMinesRoute: typeof AuthMinesRoute
  AuthProfileRoute: typeof AuthProfileRoute
}

const AuthRouteLazyRouteChildren: AuthRouteLazyRouteChildren = {
  AuthMinesRoute: AuthMinesRoute,
  AuthProfileRoute: AuthProfileRoute,
}

const AuthRouteLazyRouteWithChildren = AuthRouteLazyRoute._addFileChildren(
  AuthRouteLazyRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FairplayRoute: FairplayRoute,
  RulesRoute: RulesRoute,
  AuthRouteLazyRoute: AuthRouteLazyRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
