/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './src/routes/__root'
import { Route as SupportRouteImport } from './src/routes/support'
import { Route as BrowseRouteImport } from './src/routes/browse'
import { Route as IndexRouteImport } from './src/routes/index'
import { Route as SupportIndexRouteImport } from './src/routes/support/index'
import { Route as SupportPrincipalRouteImport } from './src/routes/support/$principal'
import { Route as AuthorPrincipalRouteImport } from './src/routes/author.$principal'
import { Route as ArticleArweaveIdRouteImport } from './src/routes/article.$arweaveId'
import { Route as AuthWriteRouteImport } from './src/routes/_auth/write'
import { Route as AuthProfileRouteImport } from './src/routes/_auth/profile'

const AuthRouteLazyRouteImport = createFileRoute('/_auth')()

const AuthRouteLazyRoute = AuthRouteLazyRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./src/routes/_auth/route.lazy').then((d) => d.Route),
)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const BrowseRoute = BrowseRouteImport.update({
  id: '/browse',
  path: '/browse',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./src/routes/browse.lazy').then((d) => d.Route))
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./src/routes/index.lazy').then((d) => d.Route))
const SupportIndexRoute = SupportIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SupportRoute,
} as any).lazy(() =>
  import('./src/routes/support/index.lazy').then((d) => d.Route),
)
const SupportPrincipalRoute = SupportPrincipalRouteImport.update({
  id: '/$principal',
  path: '/$principal',
  getParentRoute: () => SupportRoute,
} as any).lazy(() =>
  import('./src/routes/support/$principal.lazy').then((d) => d.Route),
)
const AuthorPrincipalRoute = AuthorPrincipalRouteImport.update({
  id: '/author/$principal',
  path: '/author/$principal',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./src/routes/author.$principal.lazy').then((d) => d.Route),
)
const ArticleArweaveIdRoute = ArticleArweaveIdRouteImport.update({
  id: '/article/$arweaveId',
  path: '/article/$arweaveId',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./src/routes/article.$arweaveId.lazy').then((d) => d.Route),
)
const AuthWriteRoute = AuthWriteRouteImport.update({
  id: '/write',
  path: '/write',
  getParentRoute: () => AuthRouteLazyRoute,
} as any).lazy(() =>
  import('./src/routes/_auth/write.lazy').then((d) => d.Route),
)
const AuthProfileRoute = AuthProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthRouteLazyRoute,
} as any).lazy(() =>
  import('./src/routes/_auth/profile.lazy').then((d) => d.Route),
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/browse': typeof BrowseRoute
  '/support': typeof SupportRouteWithChildren
  '/profile': typeof AuthProfileRoute
  '/write': typeof AuthWriteRoute
  '/article/$arweaveId': typeof ArticleArweaveIdRoute
  '/author/$principal': typeof AuthorPrincipalRoute
  '/support/$principal': typeof SupportPrincipalRoute
  '/support/': typeof SupportIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/browse': typeof BrowseRoute
  '/profile': typeof AuthProfileRoute
  '/write': typeof AuthWriteRoute
  '/article/$arweaveId': typeof ArticleArweaveIdRoute
  '/author/$principal': typeof AuthorPrincipalRoute
  '/support/$principal': typeof SupportPrincipalRoute
  '/support': typeof SupportIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/browse': typeof BrowseRoute
  '/support': typeof SupportRouteWithChildren
  '/_auth': typeof AuthRouteLazyRouteWithChildren
  '/_auth/profile': typeof AuthProfileRoute
  '/_auth/write': typeof AuthWriteRoute
  '/article/$arweaveId': typeof ArticleArweaveIdRoute
  '/author/$principal': typeof AuthorPrincipalRoute
  '/support/$principal': typeof SupportPrincipalRoute
  '/support/': typeof SupportIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/browse'
    | '/support'
    | '/profile'
    | '/write'
    | '/article/$arweaveId'
    | '/author/$principal'
    | '/support/$principal'
    | '/support/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/browse'
    | '/profile'
    | '/write'
    | '/article/$arweaveId'
    | '/author/$principal'
    | '/support/$principal'
    | '/support'
  id:
    | '__root__'
    | '/'
    | '/browse'
    | '/support'
    | '/_auth'
    | '/_auth/profile'
    | '/_auth/write'
    | '/article/$arweaveId'
    | '/author/$principal'
    | '/support/$principal'
    | '/support/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BrowseRoute: typeof BrowseRoute
  SupportRoute: typeof SupportRouteWithChildren
  AuthRouteLazyRoute: typeof AuthRouteLazyRouteWithChildren
  ArticleArweaveIdRoute: typeof ArticleArweaveIdRoute
  AuthorPrincipalRoute: typeof AuthorPrincipalRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/browse': {
      id: '/browse'
      path: '/browse'
      fullPath: '/browse'
      preLoaderRoute: typeof BrowseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support/': {
      id: '/support/'
      path: '/'
      fullPath: '/support/'
      preLoaderRoute: typeof SupportIndexRouteImport
      parentRoute: typeof SupportRoute
    }
    '/support/$principal': {
      id: '/support/$principal'
      path: '/$principal'
      fullPath: '/support/$principal'
      preLoaderRoute: typeof SupportPrincipalRouteImport
      parentRoute: typeof SupportRoute
    }
    '/author/$principal': {
      id: '/author/$principal'
      path: '/author/$principal'
      fullPath: '/author/$principal'
      preLoaderRoute: typeof AuthorPrincipalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/article/$arweaveId': {
      id: '/article/$arweaveId'
      path: '/article/$arweaveId'
      fullPath: '/article/$arweaveId'
      preLoaderRoute: typeof ArticleArweaveIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/write': {
      id: '/_auth/write'
      path: '/write'
      fullPath: '/write'
      preLoaderRoute: typeof AuthWriteRouteImport
      parentRoute: typeof AuthRouteLazyRoute
    }
    '/_auth/profile': {
      id: '/_auth/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthProfileRouteImport
      parentRoute: typeof AuthRouteLazyRoute
    }
  }
}

interface SupportRouteChildren {
  SupportPrincipalRoute: typeof SupportPrincipalRoute
  SupportIndexRoute: typeof SupportIndexRoute
}

const SupportRouteChildren: SupportRouteChildren = {
  SupportPrincipalRoute: SupportPrincipalRoute,
  SupportIndexRoute: SupportIndexRoute,
}

const SupportRouteWithChildren =
  SupportRoute._addFileChildren(SupportRouteChildren)

interface AuthRouteLazyRouteChildren {
  AuthProfileRoute: typeof AuthProfileRoute
  AuthWriteRoute: typeof AuthWriteRoute
}

const AuthRouteLazyRouteChildren: AuthRouteLazyRouteChildren = {
  AuthProfileRoute: AuthProfileRoute,
  AuthWriteRoute: AuthWriteRoute,
}

const AuthRouteLazyRouteWithChildren = AuthRouteLazyRoute._addFileChildren(
  AuthRouteLazyRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BrowseRoute: BrowseRoute,
  SupportRoute: SupportRouteWithChildren,
  AuthRouteLazyRoute: AuthRouteLazyRouteWithChildren,
  ArticleArweaveIdRoute: ArticleArweaveIdRoute,
  AuthorPrincipalRoute: AuthorPrincipalRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
