/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './src/routes/__root'
import { Route as IndexRouteImport } from './src/routes/index'
import { Route as AuthUploadRouteImport } from './src/routes/_auth/upload'
import { Route as AuthStudioRouteImport } from './src/routes/_auth/studio'
import { Route as AuthRecordRouteImport } from './src/routes/_auth/record'
import { Route as AuthMarketRouteImport } from './src/routes/_auth/market'
import { Route as AuthBrowseRouteImport } from './src/routes/_auth/browse'
import { Route as AuthArchiveRouteImport } from './src/routes/_auth/archive'
import { Route as AuthStudioPrincipalRouteImport } from './src/routes/_auth/studio.$principal'
import { Route as AuthArchivePrincipalRouteImport } from './src/routes/_auth/archive.$principal'

const AuthRouteLazyRouteImport = createFileRoute('/_auth')()

const AuthRouteLazyRoute = AuthRouteLazyRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./src/routes/_auth/route.lazy').then((d) => d.Route),
)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./src/routes/index.lazy').then((d) => d.Route))
const AuthUploadRoute = AuthUploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => AuthRouteLazyRoute,
} as any).lazy(() =>
  import('./src/routes/_auth/upload.lazy').then((d) => d.Route),
)
const AuthStudioRoute = AuthStudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => AuthRouteLazyRoute,
} as any).lazy(() =>
  import('./src/routes/_auth/studio.lazy').then((d) => d.Route),
)
const AuthRecordRoute = AuthRecordRouteImport.update({
  id: '/record',
  path: '/record',
  getParentRoute: () => AuthRouteLazyRoute,
} as any).lazy(() =>
  import('./src/routes/_auth/record.lazy').then((d) => d.Route),
)
const AuthMarketRoute = AuthMarketRouteImport.update({
  id: '/market',
  path: '/market',
  getParentRoute: () => AuthRouteLazyRoute,
} as any).lazy(() =>
  import('./src/routes/_auth/market.lazy').then((d) => d.Route),
)
const AuthBrowseRoute = AuthBrowseRouteImport.update({
  id: '/browse',
  path: '/browse',
  getParentRoute: () => AuthRouteLazyRoute,
} as any).lazy(() =>
  import('./src/routes/_auth/browse.lazy').then((d) => d.Route),
)
const AuthArchiveRoute = AuthArchiveRouteImport.update({
  id: '/archive',
  path: '/archive',
  getParentRoute: () => AuthRouteLazyRoute,
} as any).lazy(() =>
  import('./src/routes/_auth/archive.lazy').then((d) => d.Route),
)
const AuthStudioPrincipalRoute = AuthStudioPrincipalRouteImport.update({
  id: '/$principal',
  path: '/$principal',
  getParentRoute: () => AuthStudioRoute,
} as any).lazy(() =>
  import('./src/routes/_auth/studio.$principal.lazy').then((d) => d.Route),
)
const AuthArchivePrincipalRoute = AuthArchivePrincipalRouteImport.update({
  id: '/$principal',
  path: '/$principal',
  getParentRoute: () => AuthArchiveRoute,
} as any).lazy(() =>
  import('./src/routes/_auth/archive.$principal.lazy').then((d) => d.Route),
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/archive': typeof AuthArchiveRouteWithChildren
  '/browse': typeof AuthBrowseRoute
  '/market': typeof AuthMarketRoute
  '/record': typeof AuthRecordRoute
  '/studio': typeof AuthStudioRouteWithChildren
  '/upload': typeof AuthUploadRoute
  '/archive/$principal': typeof AuthArchivePrincipalRoute
  '/studio/$principal': typeof AuthStudioPrincipalRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/archive': typeof AuthArchiveRouteWithChildren
  '/browse': typeof AuthBrowseRoute
  '/market': typeof AuthMarketRoute
  '/record': typeof AuthRecordRoute
  '/studio': typeof AuthStudioRouteWithChildren
  '/upload': typeof AuthUploadRoute
  '/archive/$principal': typeof AuthArchivePrincipalRoute
  '/studio/$principal': typeof AuthStudioPrincipalRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteLazyRouteWithChildren
  '/_auth/archive': typeof AuthArchiveRouteWithChildren
  '/_auth/browse': typeof AuthBrowseRoute
  '/_auth/market': typeof AuthMarketRoute
  '/_auth/record': typeof AuthRecordRoute
  '/_auth/studio': typeof AuthStudioRouteWithChildren
  '/_auth/upload': typeof AuthUploadRoute
  '/_auth/archive/$principal': typeof AuthArchivePrincipalRoute
  '/_auth/studio/$principal': typeof AuthStudioPrincipalRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/archive'
    | '/browse'
    | '/market'
    | '/record'
    | '/studio'
    | '/upload'
    | '/archive/$principal'
    | '/studio/$principal'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/archive'
    | '/browse'
    | '/market'
    | '/record'
    | '/studio'
    | '/upload'
    | '/archive/$principal'
    | '/studio/$principal'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/_auth/archive'
    | '/_auth/browse'
    | '/_auth/market'
    | '/_auth/record'
    | '/_auth/studio'
    | '/_auth/upload'
    | '/_auth/archive/$principal'
    | '/_auth/studio/$principal'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRouteLazyRoute: typeof AuthRouteLazyRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/upload': {
      id: '/_auth/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof AuthUploadRouteImport
      parentRoute: typeof AuthRouteLazyRoute
    }
    '/_auth/studio': {
      id: '/_auth/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof AuthStudioRouteImport
      parentRoute: typeof AuthRouteLazyRoute
    }
    '/_auth/record': {
      id: '/_auth/record'
      path: '/record'
      fullPath: '/record'
      preLoaderRoute: typeof AuthRecordRouteImport
      parentRoute: typeof AuthRouteLazyRoute
    }
    '/_auth/market': {
      id: '/_auth/market'
      path: '/market'
      fullPath: '/market'
      preLoaderRoute: typeof AuthMarketRouteImport
      parentRoute: typeof AuthRouteLazyRoute
    }
    '/_auth/browse': {
      id: '/_auth/browse'
      path: '/browse'
      fullPath: '/browse'
      preLoaderRoute: typeof AuthBrowseRouteImport
      parentRoute: typeof AuthRouteLazyRoute
    }
    '/_auth/archive': {
      id: '/_auth/archive'
      path: '/archive'
      fullPath: '/archive'
      preLoaderRoute: typeof AuthArchiveRouteImport
      parentRoute: typeof AuthRouteLazyRoute
    }
    '/_auth/studio/$principal': {
      id: '/_auth/studio/$principal'
      path: '/$principal'
      fullPath: '/studio/$principal'
      preLoaderRoute: typeof AuthStudioPrincipalRouteImport
      parentRoute: typeof AuthStudioRoute
    }
    '/_auth/archive/$principal': {
      id: '/_auth/archive/$principal'
      path: '/$principal'
      fullPath: '/archive/$principal'
      preLoaderRoute: typeof AuthArchivePrincipalRouteImport
      parentRoute: typeof AuthArchiveRoute
    }
  }
}

interface AuthArchiveRouteChildren {
  AuthArchivePrincipalRoute: typeof AuthArchivePrincipalRoute
}

const AuthArchiveRouteChildren: AuthArchiveRouteChildren = {
  AuthArchivePrincipalRoute: AuthArchivePrincipalRoute,
}

const AuthArchiveRouteWithChildren = AuthArchiveRoute._addFileChildren(
  AuthArchiveRouteChildren,
)

interface AuthStudioRouteChildren {
  AuthStudioPrincipalRoute: typeof AuthStudioPrincipalRoute
}

const AuthStudioRouteChildren: AuthStudioRouteChildren = {
  AuthStudioPrincipalRoute: AuthStudioPrincipalRoute,
}

const AuthStudioRouteWithChildren = AuthStudioRoute._addFileChildren(
  AuthStudioRouteChildren,
)

interface AuthRouteLazyRouteChildren {
  AuthArchiveRoute: typeof AuthArchiveRouteWithChildren
  AuthBrowseRoute: typeof AuthBrowseRoute
  AuthMarketRoute: typeof AuthMarketRoute
  AuthRecordRoute: typeof AuthRecordRoute
  AuthStudioRoute: typeof AuthStudioRouteWithChildren
  AuthUploadRoute: typeof AuthUploadRoute
}

const AuthRouteLazyRouteChildren: AuthRouteLazyRouteChildren = {
  AuthArchiveRoute: AuthArchiveRouteWithChildren,
  AuthBrowseRoute: AuthBrowseRoute,
  AuthMarketRoute: AuthMarketRoute,
  AuthRecordRoute: AuthRecordRoute,
  AuthStudioRoute: AuthStudioRouteWithChildren,
  AuthUploadRoute: AuthUploadRoute,
}

const AuthRouteLazyRouteWithChildren = AuthRouteLazyRoute._addFileChildren(
  AuthRouteLazyRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRouteLazyRoute: AuthRouteLazyRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
