/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './src/routes/__root'
import { Route as TokenomicsRouteImport } from './src/routes/tokenomics'
import { Route as StatusRouteImport } from './src/routes/status'
import { Route as IndexRouteImport } from './src/routes/index'
import { Route as SwapInsightsRouteImport } from './src/routes/swap/insights'
import { Route as NftTokenIdRouteImport } from './src/routes/nft.$tokenId'
import { Route as AppPermasearchRouteImport } from './src/routes/app/permasearch'
import { Route as AppAlexandrianRouteImport } from './src/routes/app/alexandrian'
import { Route as AuthAppEmporiumIndexRouteImport } from './src/routes/_auth/app/emporium/index'
import { Route as AuthAppEmporiumMyLogsRouteImport } from './src/routes/_auth/app/emporium/my-logs'
import { Route as AuthAppEmporiumMarketLogsRouteImport } from './src/routes/_auth/app/emporium/market-logs'

const ManagerLazyRouteImport = createFileRoute('/manager')()
const SwapRouteLazyRouteImport = createFileRoute('/swap')()
const InfoRouteLazyRouteImport = createFileRoute('/info')()
const AuthRouteLazyRouteImport = createFileRoute('/_auth')()
const InfoIndexLazyRouteImport = createFileRoute('/info/')()
const SwapStakeLazyRouteImport = createFileRoute('/swap/stake')()
const SwapRedeemLazyRouteImport = createFileRoute('/swap/redeem')()
const SwapHistoryLazyRouteImport = createFileRoute('/swap/history')()
const InfoWhitepaperLazyRouteImport = createFileRoute('/info/whitepaper')()
const InfoFaqLazyRouteImport = createFileRoute('/info/faq')()
const InfoAuditLazyRouteImport = createFileRoute('/info/audit')()
const AuthSwapRouteLazyRouteImport = createFileRoute('/_auth/swap')()
const AuthDashboardRouteLazyRouteImport = createFileRoute('/_auth/dashboard')()
const AuthSwapIndexLazyRouteImport = createFileRoute('/_auth/swap/')()
const AuthSwapBurnLazyRouteImport = createFileRoute('/_auth/swap/burn')()
const AuthDashboardSettingsLazyRouteImport = createFileRoute(
  '/_auth/dashboard/settings',
)()
const AuthDashboardProfileLazyRouteImport = createFileRoute(
  '/_auth/dashboard/profile',
)()
const AuthDashboardIcpAssetsLazyRouteImport = createFileRoute(
  '/_auth/dashboard/icp-assets',
)()
const AuthDashboardArweaveAssetsLazyRouteImport = createFileRoute(
  '/_auth/dashboard/arweave-assets',
)()
const AuthAppPinaxLazyRouteImport = createFileRoute('/_auth/app/pinax')()
const AuthDashboardLibrarianRouteLazyRouteImport = createFileRoute(
  '/_auth/dashboard/_librarian',
)()
const AuthAppEmporiumRouteLazyRouteImport = createFileRoute(
  '/_auth/app/emporium',
)()
const AuthDashboardLibrarianIndexLazyRouteImport = createFileRoute(
  '/_auth/dashboard/_librarian/',
)()
const AuthAppPerpetuaIndexLazyRouteImport = createFileRoute(
  '/_auth/app/perpetua/',
)()
const AuthDashboardProfileUpgradeLazyRouteImport = createFileRoute(
  '/_auth/dashboard/profile/upgrade',
)()
const AuthDashboardLibrarianWalletsLazyRouteImport = createFileRoute(
  '/_auth/dashboard/_librarian/wallets',
)()
const AuthAppPerpetuaShelfShelfIdLazyRouteImport = createFileRoute(
  '/_auth/app/perpetua/shelf/$shelfId',
)()
const AuthAppPerpetuaItemItemIdLazyRouteImport = createFileRoute(
  '/_auth/app/perpetua/item/$itemId',
)()
const AuthAppPerpetuaUserUserIdIndexLazyRouteImport = createFileRoute(
  '/_auth/app/perpetua/user/$userId/',
)()
const AuthAppPerpetuaUserUserIdShelfShelfIdLazyRouteImport = createFileRoute(
  '/_auth/app/perpetua/user/$userId/shelf/$shelfId',
)()
const AuthAppPerpetuaUserUserIdItemItemIdLazyRouteImport = createFileRoute(
  '/_auth/app/perpetua/user/$userId/item/$itemId',
)()

const ManagerLazyRoute = ManagerLazyRouteImport.update({
  id: '/manager',
  path: '/manager',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./src/routes/manager.lazy').then((d) => d.Route))
const SwapRouteLazyRoute = SwapRouteLazyRouteImport.update({
  id: '/swap',
  path: '/swap',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./src/routes/swap/route.lazy').then((d) => d.Route),
)
const InfoRouteLazyRoute = InfoRouteLazyRouteImport.update({
  id: '/info',
  path: '/info',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./src/routes/info/route.lazy').then((d) => d.Route),
)
const AuthRouteLazyRoute = AuthRouteLazyRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./src/routes/_auth/route.lazy').then((d) => d.Route),
)
const TokenomicsRoute = TokenomicsRouteImport.update({
  id: '/tokenomics',
  path: '/tokenomics',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./src/routes/tokenomics.lazy').then((d) => d.Route),
)
const StatusRoute = StatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./src/routes/status.lazy').then((d) => d.Route))
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./src/routes/index.lazy').then((d) => d.Route))
const InfoIndexLazyRoute = InfoIndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => InfoRouteLazyRoute,
} as any).lazy(() =>
  import('./src/routes/info/index.lazy').then((d) => d.Route),
)
const SwapStakeLazyRoute = SwapStakeLazyRouteImport.update({
  id: '/stake',
  path: '/stake',
  getParentRoute: () => SwapRouteLazyRoute,
} as any).lazy(() =>
  import('./src/routes/swap/stake.lazy').then((d) => d.Route),
)
const SwapRedeemLazyRoute = SwapRedeemLazyRouteImport.update({
  id: '/redeem',
  path: '/redeem',
  getParentRoute: () => SwapRouteLazyRoute,
} as any).lazy(() =>
  import('./src/routes/swap/redeem.lazy').then((d) => d.Route),
)
const SwapHistoryLazyRoute = SwapHistoryLazyRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => SwapRouteLazyRoute,
} as any).lazy(() =>
  import('./src/routes/swap/history.lazy').then((d) => d.Route),
)
const InfoWhitepaperLazyRoute = InfoWhitepaperLazyRouteImport.update({
  id: '/whitepaper',
  path: '/whitepaper',
  getParentRoute: () => InfoRouteLazyRoute,
} as any).lazy(() =>
  import('./src/routes/info/whitepaper.lazy').then((d) => d.Route),
)
const InfoFaqLazyRoute = InfoFaqLazyRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => InfoRouteLazyRoute,
} as any).lazy(() => import('./src/routes/info/faq.lazy').then((d) => d.Route))
const InfoAuditLazyRoute = InfoAuditLazyRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => InfoRouteLazyRoute,
} as any).lazy(() =>
  import('./src/routes/info/audit.lazy').then((d) => d.Route),
)
const AuthSwapRouteLazyRoute = AuthSwapRouteLazyRouteImport.update({
  id: '/swap',
  path: '/swap',
  getParentRoute: () => AuthRouteLazyRoute,
} as any).lazy(() =>
  import('./src/routes/_auth/swap/route.lazy').then((d) => d.Route),
)
const AuthDashboardRouteLazyRoute = AuthDashboardRouteLazyRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthRouteLazyRoute,
} as any).lazy(() =>
  import('./src/routes/_auth/dashboard/route.lazy').then((d) => d.Route),
)
const SwapInsightsRoute = SwapInsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => SwapRouteLazyRoute,
} as any).lazy(() =>
  import('./src/routes/swap/insights.lazy').then((d) => d.Route),
)
const NftTokenIdRoute = NftTokenIdRouteImport.update({
  id: '/nft/$tokenId',
  path: '/nft/$tokenId',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./src/routes/nft.$tokenId.lazy').then((d) => d.Route),
)
const AppPermasearchRoute = AppPermasearchRouteImport.update({
  id: '/app/permasearch',
  path: '/app/permasearch',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./src/routes/app/permasearch.lazy').then((d) => d.Route),
)
const AppAlexandrianRoute = AppAlexandrianRouteImport.update({
  id: '/app/alexandrian',
  path: '/app/alexandrian',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./src/routes/app/alexandrian.lazy').then((d) => d.Route),
)
const AuthSwapIndexLazyRoute = AuthSwapIndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthSwapRouteLazyRoute,
} as any).lazy(() =>
  import('./src/routes/_auth/swap/index.lazy').then((d) => d.Route),
)
const AuthSwapBurnLazyRoute = AuthSwapBurnLazyRouteImport.update({
  id: '/burn',
  path: '/burn',
  getParentRoute: () => AuthSwapRouteLazyRoute,
} as any).lazy(() =>
  import('./src/routes/_auth/swap/burn.lazy').then((d) => d.Route),
)
const AuthDashboardSettingsLazyRoute =
  AuthDashboardSettingsLazyRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthDashboardRouteLazyRoute,
  } as any).lazy(() =>
    import('./src/routes/_auth/dashboard/settings.lazy').then((d) => d.Route),
  )
const AuthDashboardProfileLazyRoute =
  AuthDashboardProfileLazyRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => AuthDashboardRouteLazyRoute,
  } as any).lazy(() =>
    import('./src/routes/_auth/dashboard/profile.lazy').then((d) => d.Route),
  )
const AuthDashboardIcpAssetsLazyRoute =
  AuthDashboardIcpAssetsLazyRouteImport.update({
    id: '/icp-assets',
    path: '/icp-assets',
    getParentRoute: () => AuthDashboardRouteLazyRoute,
  } as any).lazy(() =>
    import('./src/routes/_auth/dashboard/icp-assets.lazy').then((d) => d.Route),
  )
const AuthDashboardArweaveAssetsLazyRoute =
  AuthDashboardArweaveAssetsLazyRouteImport.update({
    id: '/arweave-assets',
    path: '/arweave-assets',
    getParentRoute: () => AuthDashboardRouteLazyRoute,
  } as any).lazy(() =>
    import('./src/routes/_auth/dashboard/arweave-assets.lazy').then(
      (d) => d.Route,
    ),
  )
const AuthAppPinaxLazyRoute = AuthAppPinaxLazyRouteImport.update({
  id: '/app/pinax',
  path: '/app/pinax',
  getParentRoute: () => AuthRouteLazyRoute,
} as any).lazy(() =>
  import('./src/routes/_auth/app/pinax.lazy').then((d) => d.Route),
)
const AuthDashboardLibrarianRouteLazyRoute =
  AuthDashboardLibrarianRouteLazyRouteImport.update({
    id: '/_librarian',
    getParentRoute: () => AuthDashboardRouteLazyRoute,
  } as any).lazy(() =>
    import('./src/routes/_auth/dashboard/_librarian/route.lazy').then(
      (d) => d.Route,
    ),
  )
const AuthAppEmporiumRouteLazyRoute =
  AuthAppEmporiumRouteLazyRouteImport.update({
    id: '/app/emporium',
    path: '/app/emporium',
    getParentRoute: () => AuthRouteLazyRoute,
  } as any).lazy(() =>
    import('./src/routes/_auth/app/emporium/route.lazy').then((d) => d.Route),
  )
const AuthDashboardLibrarianIndexLazyRoute =
  AuthDashboardLibrarianIndexLazyRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthDashboardLibrarianRouteLazyRoute,
  } as any).lazy(() =>
    import('./src/routes/_auth/dashboard/_librarian/index.lazy').then(
      (d) => d.Route,
    ),
  )
const AuthAppPerpetuaIndexLazyRoute =
  AuthAppPerpetuaIndexLazyRouteImport.update({
    id: '/app/perpetua/',
    path: '/app/perpetua/',
    getParentRoute: () => AuthRouteLazyRoute,
  } as any).lazy(() =>
    import('./src/routes/_auth/app/perpetua/index.lazy').then((d) => d.Route),
  )
const AuthAppEmporiumIndexRoute = AuthAppEmporiumIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthAppEmporiumRouteLazyRoute,
} as any).lazy(() =>
  import('./src/routes/_auth/app/emporium/index.lazy').then((d) => d.Route),
)
const AuthDashboardProfileUpgradeLazyRoute =
  AuthDashboardProfileUpgradeLazyRouteImport.update({
    id: '/upgrade',
    path: '/upgrade',
    getParentRoute: () => AuthDashboardProfileLazyRoute,
  } as any).lazy(() =>
    import('./src/routes/_auth/dashboard/profile.upgrade.lazy').then(
      (d) => d.Route,
    ),
  )
const AuthDashboardLibrarianWalletsLazyRoute =
  AuthDashboardLibrarianWalletsLazyRouteImport.update({
    id: '/wallets',
    path: '/wallets',
    getParentRoute: () => AuthDashboardLibrarianRouteLazyRoute,
  } as any).lazy(() =>
    import('./src/routes/_auth/dashboard/_librarian/wallets.lazy').then(
      (d) => d.Route,
    ),
  )
const AuthAppEmporiumMyLogsRoute = AuthAppEmporiumMyLogsRouteImport.update({
  id: '/my-logs',
  path: '/my-logs',
  getParentRoute: () => AuthAppEmporiumRouteLazyRoute,
} as any).lazy(() =>
  import('./src/routes/_auth/app/emporium/my-logs.lazy').then((d) => d.Route),
)
const AuthAppEmporiumMarketLogsRoute =
  AuthAppEmporiumMarketLogsRouteImport.update({
    id: '/market-logs',
    path: '/market-logs',
    getParentRoute: () => AuthAppEmporiumRouteLazyRoute,
  } as any).lazy(() =>
    import('./src/routes/_auth/app/emporium/market-logs.lazy').then(
      (d) => d.Route,
    ),
  )
const AuthAppPerpetuaShelfShelfIdLazyRoute =
  AuthAppPerpetuaShelfShelfIdLazyRouteImport.update({
    id: '/app/perpetua/shelf/$shelfId',
    path: '/app/perpetua/shelf/$shelfId',
    getParentRoute: () => AuthRouteLazyRoute,
  } as any).lazy(() =>
    import('./src/routes/_auth/app/perpetua/shelf.$shelfId.lazy').then(
      (d) => d.Route,
    ),
  )
const AuthAppPerpetuaItemItemIdLazyRoute =
  AuthAppPerpetuaItemItemIdLazyRouteImport.update({
    id: '/app/perpetua/item/$itemId',
    path: '/app/perpetua/item/$itemId',
    getParentRoute: () => AuthRouteLazyRoute,
  } as any).lazy(() =>
    import('./src/routes/_auth/app/perpetua/item.$itemId.lazy').then(
      (d) => d.Route,
    ),
  )
const AuthAppPerpetuaUserUserIdIndexLazyRoute =
  AuthAppPerpetuaUserUserIdIndexLazyRouteImport.update({
    id: '/app/perpetua/user/$userId/',
    path: '/app/perpetua/user/$userId/',
    getParentRoute: () => AuthRouteLazyRoute,
  } as any).lazy(() =>
    import('./src/routes/_auth/app/perpetua/user/$userId/index.lazy').then(
      (d) => d.Route,
    ),
  )
const AuthAppPerpetuaUserUserIdShelfShelfIdLazyRoute =
  AuthAppPerpetuaUserUserIdShelfShelfIdLazyRouteImport.update({
    id: '/app/perpetua/user/$userId/shelf/$shelfId',
    path: '/app/perpetua/user/$userId/shelf/$shelfId',
    getParentRoute: () => AuthRouteLazyRoute,
  } as any).lazy(() =>
    import(
      './src/routes/_auth/app/perpetua/user/$userId/shelf.$shelfId.lazy'
    ).then((d) => d.Route),
  )
const AuthAppPerpetuaUserUserIdItemItemIdLazyRoute =
  AuthAppPerpetuaUserUserIdItemItemIdLazyRouteImport.update({
    id: '/app/perpetua/user/$userId/item/$itemId',
    path: '/app/perpetua/user/$userId/item/$itemId',
    getParentRoute: () => AuthRouteLazyRoute,
  } as any).lazy(() =>
    import(
      './src/routes/_auth/app/perpetua/user/$userId/item.$itemId.lazy'
    ).then((d) => d.Route),
  )

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/status': typeof StatusRoute
  '/tokenomics': typeof TokenomicsRoute
  '/info': typeof InfoRouteLazyRouteWithChildren
  '/swap': typeof AuthSwapRouteLazyRouteWithChildren
  '/manager': typeof ManagerLazyRoute
  '/app/alexandrian': typeof AppAlexandrianRoute
  '/app/permasearch': typeof AppPermasearchRoute
  '/nft/$tokenId': typeof NftTokenIdRoute
  '/swap/insights': typeof SwapInsightsRoute
  '/dashboard': typeof AuthDashboardLibrarianRouteLazyRouteWithChildren
  '/info/audit': typeof InfoAuditLazyRoute
  '/info/faq': typeof InfoFaqLazyRoute
  '/info/whitepaper': typeof InfoWhitepaperLazyRoute
  '/swap/history': typeof SwapHistoryLazyRoute
  '/swap/redeem': typeof SwapRedeemLazyRoute
  '/swap/stake': typeof SwapStakeLazyRoute
  '/info/': typeof InfoIndexLazyRoute
  '/app/emporium': typeof AuthAppEmporiumRouteLazyRouteWithChildren
  '/app/pinax': typeof AuthAppPinaxLazyRoute
  '/dashboard/arweave-assets': typeof AuthDashboardArweaveAssetsLazyRoute
  '/dashboard/icp-assets': typeof AuthDashboardIcpAssetsLazyRoute
  '/dashboard/profile': typeof AuthDashboardProfileLazyRouteWithChildren
  '/dashboard/settings': typeof AuthDashboardSettingsLazyRoute
  '/swap/burn': typeof AuthSwapBurnLazyRoute
  '/swap/': typeof AuthSwapIndexLazyRoute
  '/app/emporium/market-logs': typeof AuthAppEmporiumMarketLogsRoute
  '/app/emporium/my-logs': typeof AuthAppEmporiumMyLogsRoute
  '/dashboard/wallets': typeof AuthDashboardLibrarianWalletsLazyRoute
  '/dashboard/profile/upgrade': typeof AuthDashboardProfileUpgradeLazyRoute
  '/app/emporium/': typeof AuthAppEmporiumIndexRoute
  '/app/perpetua': typeof AuthAppPerpetuaIndexLazyRoute
  '/dashboard/': typeof AuthDashboardLibrarianIndexLazyRoute
  '/app/perpetua/item/$itemId': typeof AuthAppPerpetuaItemItemIdLazyRoute
  '/app/perpetua/shelf/$shelfId': typeof AuthAppPerpetuaShelfShelfIdLazyRoute
  '/app/perpetua/user/$userId': typeof AuthAppPerpetuaUserUserIdIndexLazyRoute
  '/app/perpetua/user/$userId/item/$itemId': typeof AuthAppPerpetuaUserUserIdItemItemIdLazyRoute
  '/app/perpetua/user/$userId/shelf/$shelfId': typeof AuthAppPerpetuaUserUserIdShelfShelfIdLazyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/status': typeof StatusRoute
  '/tokenomics': typeof TokenomicsRoute
  '/swap': typeof AuthSwapIndexLazyRoute
  '/manager': typeof ManagerLazyRoute
  '/app/alexandrian': typeof AppAlexandrianRoute
  '/app/permasearch': typeof AppPermasearchRoute
  '/nft/$tokenId': typeof NftTokenIdRoute
  '/swap/insights': typeof SwapInsightsRoute
  '/dashboard': typeof AuthDashboardLibrarianIndexLazyRoute
  '/info/audit': typeof InfoAuditLazyRoute
  '/info/faq': typeof InfoFaqLazyRoute
  '/info/whitepaper': typeof InfoWhitepaperLazyRoute
  '/swap/history': typeof SwapHistoryLazyRoute
  '/swap/redeem': typeof SwapRedeemLazyRoute
  '/swap/stake': typeof SwapStakeLazyRoute
  '/info': typeof InfoIndexLazyRoute
  '/app/pinax': typeof AuthAppPinaxLazyRoute
  '/dashboard/arweave-assets': typeof AuthDashboardArweaveAssetsLazyRoute
  '/dashboard/icp-assets': typeof AuthDashboardIcpAssetsLazyRoute
  '/dashboard/profile': typeof AuthDashboardProfileLazyRouteWithChildren
  '/dashboard/settings': typeof AuthDashboardSettingsLazyRoute
  '/swap/burn': typeof AuthSwapBurnLazyRoute
  '/app/emporium/market-logs': typeof AuthAppEmporiumMarketLogsRoute
  '/app/emporium/my-logs': typeof AuthAppEmporiumMyLogsRoute
  '/dashboard/wallets': typeof AuthDashboardLibrarianWalletsLazyRoute
  '/dashboard/profile/upgrade': typeof AuthDashboardProfileUpgradeLazyRoute
  '/app/emporium': typeof AuthAppEmporiumIndexRoute
  '/app/perpetua': typeof AuthAppPerpetuaIndexLazyRoute
  '/app/perpetua/item/$itemId': typeof AuthAppPerpetuaItemItemIdLazyRoute
  '/app/perpetua/shelf/$shelfId': typeof AuthAppPerpetuaShelfShelfIdLazyRoute
  '/app/perpetua/user/$userId': typeof AuthAppPerpetuaUserUserIdIndexLazyRoute
  '/app/perpetua/user/$userId/item/$itemId': typeof AuthAppPerpetuaUserUserIdItemItemIdLazyRoute
  '/app/perpetua/user/$userId/shelf/$shelfId': typeof AuthAppPerpetuaUserUserIdShelfShelfIdLazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/status': typeof StatusRoute
  '/tokenomics': typeof TokenomicsRoute
  '/_auth': typeof AuthRouteLazyRouteWithChildren
  '/info': typeof InfoRouteLazyRouteWithChildren
  '/swap': typeof SwapRouteLazyRouteWithChildren
  '/manager': typeof ManagerLazyRoute
  '/app/alexandrian': typeof AppAlexandrianRoute
  '/app/permasearch': typeof AppPermasearchRoute
  '/nft/$tokenId': typeof NftTokenIdRoute
  '/swap/insights': typeof SwapInsightsRoute
  '/_auth/dashboard': typeof AuthDashboardRouteLazyRouteWithChildren
  '/_auth/swap': typeof AuthSwapRouteLazyRouteWithChildren
  '/info/audit': typeof InfoAuditLazyRoute
  '/info/faq': typeof InfoFaqLazyRoute
  '/info/whitepaper': typeof InfoWhitepaperLazyRoute
  '/swap/history': typeof SwapHistoryLazyRoute
  '/swap/redeem': typeof SwapRedeemLazyRoute
  '/swap/stake': typeof SwapStakeLazyRoute
  '/info/': typeof InfoIndexLazyRoute
  '/_auth/app/emporium': typeof AuthAppEmporiumRouteLazyRouteWithChildren
  '/_auth/dashboard/_librarian': typeof AuthDashboardLibrarianRouteLazyRouteWithChildren
  '/_auth/app/pinax': typeof AuthAppPinaxLazyRoute
  '/_auth/dashboard/arweave-assets': typeof AuthDashboardArweaveAssetsLazyRoute
  '/_auth/dashboard/icp-assets': typeof AuthDashboardIcpAssetsLazyRoute
  '/_auth/dashboard/profile': typeof AuthDashboardProfileLazyRouteWithChildren
  '/_auth/dashboard/settings': typeof AuthDashboardSettingsLazyRoute
  '/_auth/swap/burn': typeof AuthSwapBurnLazyRoute
  '/_auth/swap/': typeof AuthSwapIndexLazyRoute
  '/_auth/app/emporium/market-logs': typeof AuthAppEmporiumMarketLogsRoute
  '/_auth/app/emporium/my-logs': typeof AuthAppEmporiumMyLogsRoute
  '/_auth/dashboard/_librarian/wallets': typeof AuthDashboardLibrarianWalletsLazyRoute
  '/_auth/dashboard/profile/upgrade': typeof AuthDashboardProfileUpgradeLazyRoute
  '/_auth/app/emporium/': typeof AuthAppEmporiumIndexRoute
  '/_auth/app/perpetua/': typeof AuthAppPerpetuaIndexLazyRoute
  '/_auth/dashboard/_librarian/': typeof AuthDashboardLibrarianIndexLazyRoute
  '/_auth/app/perpetua/item/$itemId': typeof AuthAppPerpetuaItemItemIdLazyRoute
  '/_auth/app/perpetua/shelf/$shelfId': typeof AuthAppPerpetuaShelfShelfIdLazyRoute
  '/_auth/app/perpetua/user/$userId/': typeof AuthAppPerpetuaUserUserIdIndexLazyRoute
  '/_auth/app/perpetua/user/$userId/item/$itemId': typeof AuthAppPerpetuaUserUserIdItemItemIdLazyRoute
  '/_auth/app/perpetua/user/$userId/shelf/$shelfId': typeof AuthAppPerpetuaUserUserIdShelfShelfIdLazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/status'
    | '/tokenomics'
    | '/info'
    | '/swap'
    | '/manager'
    | '/app/alexandrian'
    | '/app/permasearch'
    | '/nft/$tokenId'
    | '/swap/insights'
    | '/dashboard'
    | '/info/audit'
    | '/info/faq'
    | '/info/whitepaper'
    | '/swap/history'
    | '/swap/redeem'
    | '/swap/stake'
    | '/info/'
    | '/app/emporium'
    | '/app/pinax'
    | '/dashboard/arweave-assets'
    | '/dashboard/icp-assets'
    | '/dashboard/profile'
    | '/dashboard/settings'
    | '/swap/burn'
    | '/swap/'
    | '/app/emporium/market-logs'
    | '/app/emporium/my-logs'
    | '/dashboard/wallets'
    | '/dashboard/profile/upgrade'
    | '/app/emporium/'
    | '/app/perpetua'
    | '/dashboard/'
    | '/app/perpetua/item/$itemId'
    | '/app/perpetua/shelf/$shelfId'
    | '/app/perpetua/user/$userId'
    | '/app/perpetua/user/$userId/item/$itemId'
    | '/app/perpetua/user/$userId/shelf/$shelfId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/status'
    | '/tokenomics'
    | '/swap'
    | '/manager'
    | '/app/alexandrian'
    | '/app/permasearch'
    | '/nft/$tokenId'
    | '/swap/insights'
    | '/dashboard'
    | '/info/audit'
    | '/info/faq'
    | '/info/whitepaper'
    | '/swap/history'
    | '/swap/redeem'
    | '/swap/stake'
    | '/info'
    | '/app/pinax'
    | '/dashboard/arweave-assets'
    | '/dashboard/icp-assets'
    | '/dashboard/profile'
    | '/dashboard/settings'
    | '/swap/burn'
    | '/app/emporium/market-logs'
    | '/app/emporium/my-logs'
    | '/dashboard/wallets'
    | '/dashboard/profile/upgrade'
    | '/app/emporium'
    | '/app/perpetua'
    | '/app/perpetua/item/$itemId'
    | '/app/perpetua/shelf/$shelfId'
    | '/app/perpetua/user/$userId'
    | '/app/perpetua/user/$userId/item/$itemId'
    | '/app/perpetua/user/$userId/shelf/$shelfId'
  id:
    | '__root__'
    | '/'
    | '/status'
    | '/tokenomics'
    | '/_auth'
    | '/info'
    | '/swap'
    | '/manager'
    | '/app/alexandrian'
    | '/app/permasearch'
    | '/nft/$tokenId'
    | '/swap/insights'
    | '/_auth/dashboard'
    | '/_auth/swap'
    | '/info/audit'
    | '/info/faq'
    | '/info/whitepaper'
    | '/swap/history'
    | '/swap/redeem'
    | '/swap/stake'
    | '/info/'
    | '/_auth/app/emporium'
    | '/_auth/dashboard/_librarian'
    | '/_auth/app/pinax'
    | '/_auth/dashboard/arweave-assets'
    | '/_auth/dashboard/icp-assets'
    | '/_auth/dashboard/profile'
    | '/_auth/dashboard/settings'
    | '/_auth/swap/burn'
    | '/_auth/swap/'
    | '/_auth/app/emporium/market-logs'
    | '/_auth/app/emporium/my-logs'
    | '/_auth/dashboard/_librarian/wallets'
    | '/_auth/dashboard/profile/upgrade'
    | '/_auth/app/emporium/'
    | '/_auth/app/perpetua/'
    | '/_auth/dashboard/_librarian/'
    | '/_auth/app/perpetua/item/$itemId'
    | '/_auth/app/perpetua/shelf/$shelfId'
    | '/_auth/app/perpetua/user/$userId/'
    | '/_auth/app/perpetua/user/$userId/item/$itemId'
    | '/_auth/app/perpetua/user/$userId/shelf/$shelfId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  StatusRoute: typeof StatusRoute
  TokenomicsRoute: typeof TokenomicsRoute
  AuthRouteLazyRoute: typeof AuthRouteLazyRouteWithChildren
  InfoRouteLazyRoute: typeof InfoRouteLazyRouteWithChildren
  SwapRouteLazyRoute: typeof SwapRouteLazyRouteWithChildren
  ManagerLazyRoute: typeof ManagerLazyRoute
  AppAlexandrianRoute: typeof AppAlexandrianRoute
  AppPermasearchRoute: typeof AppPermasearchRoute
  NftTokenIdRoute: typeof NftTokenIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/manager': {
      id: '/manager'
      path: '/manager'
      fullPath: '/manager'
      preLoaderRoute: typeof ManagerLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/swap': {
      id: '/swap'
      path: '/swap'
      fullPath: '/swap'
      preLoaderRoute: typeof SwapRouteLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/info': {
      id: '/info'
      path: '/info'
      fullPath: '/info'
      preLoaderRoute: typeof InfoRouteLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tokenomics': {
      id: '/tokenomics'
      path: '/tokenomics'
      fullPath: '/tokenomics'
      preLoaderRoute: typeof TokenomicsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/status': {
      id: '/status'
      path: '/status'
      fullPath: '/status'
      preLoaderRoute: typeof StatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/info/': {
      id: '/info/'
      path: '/'
      fullPath: '/info/'
      preLoaderRoute: typeof InfoIndexLazyRouteImport
      parentRoute: typeof InfoRouteLazyRoute
    }
    '/swap/stake': {
      id: '/swap/stake'
      path: '/stake'
      fullPath: '/swap/stake'
      preLoaderRoute: typeof SwapStakeLazyRouteImport
      parentRoute: typeof SwapRouteLazyRoute
    }
    '/swap/redeem': {
      id: '/swap/redeem'
      path: '/redeem'
      fullPath: '/swap/redeem'
      preLoaderRoute: typeof SwapRedeemLazyRouteImport
      parentRoute: typeof SwapRouteLazyRoute
    }
    '/swap/history': {
      id: '/swap/history'
      path: '/history'
      fullPath: '/swap/history'
      preLoaderRoute: typeof SwapHistoryLazyRouteImport
      parentRoute: typeof SwapRouteLazyRoute
    }
    '/info/whitepaper': {
      id: '/info/whitepaper'
      path: '/whitepaper'
      fullPath: '/info/whitepaper'
      preLoaderRoute: typeof InfoWhitepaperLazyRouteImport
      parentRoute: typeof InfoRouteLazyRoute
    }
    '/info/faq': {
      id: '/info/faq'
      path: '/faq'
      fullPath: '/info/faq'
      preLoaderRoute: typeof InfoFaqLazyRouteImport
      parentRoute: typeof InfoRouteLazyRoute
    }
    '/info/audit': {
      id: '/info/audit'
      path: '/audit'
      fullPath: '/info/audit'
      preLoaderRoute: typeof InfoAuditLazyRouteImport
      parentRoute: typeof InfoRouteLazyRoute
    }
    '/_auth/swap': {
      id: '/_auth/swap'
      path: '/swap'
      fullPath: '/swap'
      preLoaderRoute: typeof AuthSwapRouteLazyRouteImport
      parentRoute: typeof AuthRouteLazyRoute
    }
    '/_auth/dashboard': {
      id: '/_auth/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthDashboardRouteLazyRouteImport
      parentRoute: typeof AuthRouteLazyRoute
    }
    '/swap/insights': {
      id: '/swap/insights'
      path: '/insights'
      fullPath: '/swap/insights'
      preLoaderRoute: typeof SwapInsightsRouteImport
      parentRoute: typeof SwapRouteLazyRoute
    }
    '/nft/$tokenId': {
      id: '/nft/$tokenId'
      path: '/nft/$tokenId'
      fullPath: '/nft/$tokenId'
      preLoaderRoute: typeof NftTokenIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/permasearch': {
      id: '/app/permasearch'
      path: '/app/permasearch'
      fullPath: '/app/permasearch'
      preLoaderRoute: typeof AppPermasearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/alexandrian': {
      id: '/app/alexandrian'
      path: '/app/alexandrian'
      fullPath: '/app/alexandrian'
      preLoaderRoute: typeof AppAlexandrianRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/swap/': {
      id: '/_auth/swap/'
      path: '/'
      fullPath: '/swap/'
      preLoaderRoute: typeof AuthSwapIndexLazyRouteImport
      parentRoute: typeof AuthSwapRouteLazyRoute
    }
    '/_auth/swap/burn': {
      id: '/_auth/swap/burn'
      path: '/burn'
      fullPath: '/swap/burn'
      preLoaderRoute: typeof AuthSwapBurnLazyRouteImport
      parentRoute: typeof AuthSwapRouteLazyRoute
    }
    '/_auth/dashboard/settings': {
      id: '/_auth/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof AuthDashboardSettingsLazyRouteImport
      parentRoute: typeof AuthDashboardRouteLazyRoute
    }
    '/_auth/dashboard/profile': {
      id: '/_auth/dashboard/profile'
      path: '/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof AuthDashboardProfileLazyRouteImport
      parentRoute: typeof AuthDashboardRouteLazyRoute
    }
    '/_auth/dashboard/icp-assets': {
      id: '/_auth/dashboard/icp-assets'
      path: '/icp-assets'
      fullPath: '/dashboard/icp-assets'
      preLoaderRoute: typeof AuthDashboardIcpAssetsLazyRouteImport
      parentRoute: typeof AuthDashboardRouteLazyRoute
    }
    '/_auth/dashboard/arweave-assets': {
      id: '/_auth/dashboard/arweave-assets'
      path: '/arweave-assets'
      fullPath: '/dashboard/arweave-assets'
      preLoaderRoute: typeof AuthDashboardArweaveAssetsLazyRouteImport
      parentRoute: typeof AuthDashboardRouteLazyRoute
    }
    '/_auth/app/pinax': {
      id: '/_auth/app/pinax'
      path: '/app/pinax'
      fullPath: '/app/pinax'
      preLoaderRoute: typeof AuthAppPinaxLazyRouteImport
      parentRoute: typeof AuthRouteLazyRoute
    }
    '/_auth/dashboard/_librarian': {
      id: '/_auth/dashboard/_librarian'
      path: ''
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthDashboardLibrarianRouteLazyRouteImport
      parentRoute: typeof AuthDashboardRouteLazyRoute
    }
    '/_auth/app/emporium': {
      id: '/_auth/app/emporium'
      path: '/app/emporium'
      fullPath: '/app/emporium'
      preLoaderRoute: typeof AuthAppEmporiumRouteLazyRouteImport
      parentRoute: typeof AuthRouteLazyRoute
    }
    '/_auth/dashboard/_librarian/': {
      id: '/_auth/dashboard/_librarian/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthDashboardLibrarianIndexLazyRouteImport
      parentRoute: typeof AuthDashboardLibrarianRouteLazyRoute
    }
    '/_auth/app/perpetua/': {
      id: '/_auth/app/perpetua/'
      path: '/app/perpetua'
      fullPath: '/app/perpetua'
      preLoaderRoute: typeof AuthAppPerpetuaIndexLazyRouteImport
      parentRoute: typeof AuthRouteLazyRoute
    }
    '/_auth/app/emporium/': {
      id: '/_auth/app/emporium/'
      path: '/'
      fullPath: '/app/emporium/'
      preLoaderRoute: typeof AuthAppEmporiumIndexRouteImport
      parentRoute: typeof AuthAppEmporiumRouteLazyRoute
    }
    '/_auth/dashboard/profile/upgrade': {
      id: '/_auth/dashboard/profile/upgrade'
      path: '/upgrade'
      fullPath: '/dashboard/profile/upgrade'
      preLoaderRoute: typeof AuthDashboardProfileUpgradeLazyRouteImport
      parentRoute: typeof AuthDashboardProfileLazyRoute
    }
    '/_auth/dashboard/_librarian/wallets': {
      id: '/_auth/dashboard/_librarian/wallets'
      path: '/wallets'
      fullPath: '/dashboard/wallets'
      preLoaderRoute: typeof AuthDashboardLibrarianWalletsLazyRouteImport
      parentRoute: typeof AuthDashboardLibrarianRouteLazyRoute
    }
    '/_auth/app/emporium/my-logs': {
      id: '/_auth/app/emporium/my-logs'
      path: '/my-logs'
      fullPath: '/app/emporium/my-logs'
      preLoaderRoute: typeof AuthAppEmporiumMyLogsRouteImport
      parentRoute: typeof AuthAppEmporiumRouteLazyRoute
    }
    '/_auth/app/emporium/market-logs': {
      id: '/_auth/app/emporium/market-logs'
      path: '/market-logs'
      fullPath: '/app/emporium/market-logs'
      preLoaderRoute: typeof AuthAppEmporiumMarketLogsRouteImport
      parentRoute: typeof AuthAppEmporiumRouteLazyRoute
    }
    '/_auth/app/perpetua/shelf/$shelfId': {
      id: '/_auth/app/perpetua/shelf/$shelfId'
      path: '/app/perpetua/shelf/$shelfId'
      fullPath: '/app/perpetua/shelf/$shelfId'
      preLoaderRoute: typeof AuthAppPerpetuaShelfShelfIdLazyRouteImport
      parentRoute: typeof AuthRouteLazyRoute
    }
    '/_auth/app/perpetua/item/$itemId': {
      id: '/_auth/app/perpetua/item/$itemId'
      path: '/app/perpetua/item/$itemId'
      fullPath: '/app/perpetua/item/$itemId'
      preLoaderRoute: typeof AuthAppPerpetuaItemItemIdLazyRouteImport
      parentRoute: typeof AuthRouteLazyRoute
    }
    '/_auth/app/perpetua/user/$userId/': {
      id: '/_auth/app/perpetua/user/$userId/'
      path: '/app/perpetua/user/$userId'
      fullPath: '/app/perpetua/user/$userId'
      preLoaderRoute: typeof AuthAppPerpetuaUserUserIdIndexLazyRouteImport
      parentRoute: typeof AuthRouteLazyRoute
    }
    '/_auth/app/perpetua/user/$userId/shelf/$shelfId': {
      id: '/_auth/app/perpetua/user/$userId/shelf/$shelfId'
      path: '/app/perpetua/user/$userId/shelf/$shelfId'
      fullPath: '/app/perpetua/user/$userId/shelf/$shelfId'
      preLoaderRoute: typeof AuthAppPerpetuaUserUserIdShelfShelfIdLazyRouteImport
      parentRoute: typeof AuthRouteLazyRoute
    }
    '/_auth/app/perpetua/user/$userId/item/$itemId': {
      id: '/_auth/app/perpetua/user/$userId/item/$itemId'
      path: '/app/perpetua/user/$userId/item/$itemId'
      fullPath: '/app/perpetua/user/$userId/item/$itemId'
      preLoaderRoute: typeof AuthAppPerpetuaUserUserIdItemItemIdLazyRouteImport
      parentRoute: typeof AuthRouteLazyRoute
    }
  }
}

interface AuthDashboardLibrarianRouteLazyRouteChildren {
  AuthDashboardLibrarianWalletsLazyRoute: typeof AuthDashboardLibrarianWalletsLazyRoute
  AuthDashboardLibrarianIndexLazyRoute: typeof AuthDashboardLibrarianIndexLazyRoute
}

const AuthDashboardLibrarianRouteLazyRouteChildren: AuthDashboardLibrarianRouteLazyRouteChildren =
  {
    AuthDashboardLibrarianWalletsLazyRoute:
      AuthDashboardLibrarianWalletsLazyRoute,
    AuthDashboardLibrarianIndexLazyRoute: AuthDashboardLibrarianIndexLazyRoute,
  }

const AuthDashboardLibrarianRouteLazyRouteWithChildren =
  AuthDashboardLibrarianRouteLazyRoute._addFileChildren(
    AuthDashboardLibrarianRouteLazyRouteChildren,
  )

interface AuthDashboardProfileLazyRouteChildren {
  AuthDashboardProfileUpgradeLazyRoute: typeof AuthDashboardProfileUpgradeLazyRoute
}

const AuthDashboardProfileLazyRouteChildren: AuthDashboardProfileLazyRouteChildren =
  {
    AuthDashboardProfileUpgradeLazyRoute: AuthDashboardProfileUpgradeLazyRoute,
  }

const AuthDashboardProfileLazyRouteWithChildren =
  AuthDashboardProfileLazyRoute._addFileChildren(
    AuthDashboardProfileLazyRouteChildren,
  )

interface AuthDashboardRouteLazyRouteChildren {
  AuthDashboardLibrarianRouteLazyRoute: typeof AuthDashboardLibrarianRouteLazyRouteWithChildren
  AuthDashboardArweaveAssetsLazyRoute: typeof AuthDashboardArweaveAssetsLazyRoute
  AuthDashboardIcpAssetsLazyRoute: typeof AuthDashboardIcpAssetsLazyRoute
  AuthDashboardProfileLazyRoute: typeof AuthDashboardProfileLazyRouteWithChildren
  AuthDashboardSettingsLazyRoute: typeof AuthDashboardSettingsLazyRoute
}

const AuthDashboardRouteLazyRouteChildren: AuthDashboardRouteLazyRouteChildren =
  {
    AuthDashboardLibrarianRouteLazyRoute:
      AuthDashboardLibrarianRouteLazyRouteWithChildren,
    AuthDashboardArweaveAssetsLazyRoute: AuthDashboardArweaveAssetsLazyRoute,
    AuthDashboardIcpAssetsLazyRoute: AuthDashboardIcpAssetsLazyRoute,
    AuthDashboardProfileLazyRoute: AuthDashboardProfileLazyRouteWithChildren,
    AuthDashboardSettingsLazyRoute: AuthDashboardSettingsLazyRoute,
  }

const AuthDashboardRouteLazyRouteWithChildren =
  AuthDashboardRouteLazyRoute._addFileChildren(
    AuthDashboardRouteLazyRouteChildren,
  )

interface AuthSwapRouteLazyRouteChildren {
  AuthSwapBurnLazyRoute: typeof AuthSwapBurnLazyRoute
  AuthSwapIndexLazyRoute: typeof AuthSwapIndexLazyRoute
}

const AuthSwapRouteLazyRouteChildren: AuthSwapRouteLazyRouteChildren = {
  AuthSwapBurnLazyRoute: AuthSwapBurnLazyRoute,
  AuthSwapIndexLazyRoute: AuthSwapIndexLazyRoute,
}

const AuthSwapRouteLazyRouteWithChildren =
  AuthSwapRouteLazyRoute._addFileChildren(AuthSwapRouteLazyRouteChildren)

interface AuthAppEmporiumRouteLazyRouteChildren {
  AuthAppEmporiumMarketLogsRoute: typeof AuthAppEmporiumMarketLogsRoute
  AuthAppEmporiumMyLogsRoute: typeof AuthAppEmporiumMyLogsRoute
  AuthAppEmporiumIndexRoute: typeof AuthAppEmporiumIndexRoute
}

const AuthAppEmporiumRouteLazyRouteChildren: AuthAppEmporiumRouteLazyRouteChildren =
  {
    AuthAppEmporiumMarketLogsRoute: AuthAppEmporiumMarketLogsRoute,
    AuthAppEmporiumMyLogsRoute: AuthAppEmporiumMyLogsRoute,
    AuthAppEmporiumIndexRoute: AuthAppEmporiumIndexRoute,
  }

const AuthAppEmporiumRouteLazyRouteWithChildren =
  AuthAppEmporiumRouteLazyRoute._addFileChildren(
    AuthAppEmporiumRouteLazyRouteChildren,
  )

interface AuthRouteLazyRouteChildren {
  AuthDashboardRouteLazyRoute: typeof AuthDashboardRouteLazyRouteWithChildren
  AuthSwapRouteLazyRoute: typeof AuthSwapRouteLazyRouteWithChildren
  AuthAppEmporiumRouteLazyRoute: typeof AuthAppEmporiumRouteLazyRouteWithChildren
  AuthAppPinaxLazyRoute: typeof AuthAppPinaxLazyRoute
  AuthAppPerpetuaIndexLazyRoute: typeof AuthAppPerpetuaIndexLazyRoute
  AuthAppPerpetuaItemItemIdLazyRoute: typeof AuthAppPerpetuaItemItemIdLazyRoute
  AuthAppPerpetuaShelfShelfIdLazyRoute: typeof AuthAppPerpetuaShelfShelfIdLazyRoute
  AuthAppPerpetuaUserUserIdIndexLazyRoute: typeof AuthAppPerpetuaUserUserIdIndexLazyRoute
  AuthAppPerpetuaUserUserIdItemItemIdLazyRoute: typeof AuthAppPerpetuaUserUserIdItemItemIdLazyRoute
  AuthAppPerpetuaUserUserIdShelfShelfIdLazyRoute: typeof AuthAppPerpetuaUserUserIdShelfShelfIdLazyRoute
}

const AuthRouteLazyRouteChildren: AuthRouteLazyRouteChildren = {
  AuthDashboardRouteLazyRoute: AuthDashboardRouteLazyRouteWithChildren,
  AuthSwapRouteLazyRoute: AuthSwapRouteLazyRouteWithChildren,
  AuthAppEmporiumRouteLazyRoute: AuthAppEmporiumRouteLazyRouteWithChildren,
  AuthAppPinaxLazyRoute: AuthAppPinaxLazyRoute,
  AuthAppPerpetuaIndexLazyRoute: AuthAppPerpetuaIndexLazyRoute,
  AuthAppPerpetuaItemItemIdLazyRoute: AuthAppPerpetuaItemItemIdLazyRoute,
  AuthAppPerpetuaShelfShelfIdLazyRoute: AuthAppPerpetuaShelfShelfIdLazyRoute,
  AuthAppPerpetuaUserUserIdIndexLazyRoute:
    AuthAppPerpetuaUserUserIdIndexLazyRoute,
  AuthAppPerpetuaUserUserIdItemItemIdLazyRoute:
    AuthAppPerpetuaUserUserIdItemItemIdLazyRoute,
  AuthAppPerpetuaUserUserIdShelfShelfIdLazyRoute:
    AuthAppPerpetuaUserUserIdShelfShelfIdLazyRoute,
}

const AuthRouteLazyRouteWithChildren = AuthRouteLazyRoute._addFileChildren(
  AuthRouteLazyRouteChildren,
)

interface InfoRouteLazyRouteChildren {
  InfoAuditLazyRoute: typeof InfoAuditLazyRoute
  InfoFaqLazyRoute: typeof InfoFaqLazyRoute
  InfoWhitepaperLazyRoute: typeof InfoWhitepaperLazyRoute
  InfoIndexLazyRoute: typeof InfoIndexLazyRoute
}

const InfoRouteLazyRouteChildren: InfoRouteLazyRouteChildren = {
  InfoAuditLazyRoute: InfoAuditLazyRoute,
  InfoFaqLazyRoute: InfoFaqLazyRoute,
  InfoWhitepaperLazyRoute: InfoWhitepaperLazyRoute,
  InfoIndexLazyRoute: InfoIndexLazyRoute,
}

const InfoRouteLazyRouteWithChildren = InfoRouteLazyRoute._addFileChildren(
  InfoRouteLazyRouteChildren,
)

interface SwapRouteLazyRouteChildren {
  SwapInsightsRoute: typeof SwapInsightsRoute
  SwapHistoryLazyRoute: typeof SwapHistoryLazyRoute
  SwapRedeemLazyRoute: typeof SwapRedeemLazyRoute
  SwapStakeLazyRoute: typeof SwapStakeLazyRoute
}

const SwapRouteLazyRouteChildren: SwapRouteLazyRouteChildren = {
  SwapInsightsRoute: SwapInsightsRoute,
  SwapHistoryLazyRoute: SwapHistoryLazyRoute,
  SwapRedeemLazyRoute: SwapRedeemLazyRoute,
  SwapStakeLazyRoute: SwapStakeLazyRoute,
}

const SwapRouteLazyRouteWithChildren = SwapRouteLazyRoute._addFileChildren(
  SwapRouteLazyRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  StatusRoute: StatusRoute,
  TokenomicsRoute: TokenomicsRoute,
  AuthRouteLazyRoute: AuthRouteLazyRouteWithChildren,
  InfoRouteLazyRoute: InfoRouteLazyRouteWithChildren,
  SwapRouteLazyRoute: SwapRouteLazyRouteWithChildren,
  ManagerLazyRoute: ManagerLazyRoute,
  AppAlexandrianRoute: AppAlexandrianRoute,
  AppPermasearchRoute: AppPermasearchRoute,
  NftTokenIdRoute: NftTokenIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
